// `vitest/config` rather than `vite`, so the `test` block below is typed. It re-exports
// Vite's own `defineConfig` and adds nothing to the build.
import { defineConfig } from 'vitest/config';
import { svelte } from '@sveltejs/vite-plugin-svelte';

// Tauri drives this dev server; the port is fixed so tauri.conf.json can point at it.
export default defineConfig({
	plugins: [svelte()],
	clearScreen: false,
	server: {
		port: 1420,
		strictPort: true,
		watch: {
			// **`target/` is not source.** Cargo's output directory holds ~250 000 files here, against
			// 61 under `src/`, and the watcher walks and re-stats every one of them: without
			// `fsevents` installed, chokidar polls, which is a `stat` per file per interval. That is
			// 4-and-a-half cores burnt and 1.4 GB of cached stat entries on an idle map — plus the
			// occasional page reload when a build script writes an HTML file into a GDAL output
			// directory, which is the visible half of the same bug.
			//
			// Vite merges this with its own list (`.git`, `node_modules`, the cache directory), so
			// naming one pattern here does not give the others up. `**/target/**` covers both the
			// workspace's and `src-tauri`'s.
			ignored: ['**/target/**']
		}
	},
	test: {
		coverage: {
			// V8's own counters rather than instrumenting the source: no Babel pass, and what is
			// measured is the code that actually ran.
			provider: 'v8',
			// `text` for a human watching the run, `lcov` for Codecov, `json-summary` so a failure can
			// say the number without anyone opening a report.
			reporter: ['text', 'lcov', 'json-summary'],
			reportsDirectory: 'coverage',

			// **Everything that could be tested, whether it is or not.** Vitest reports every file
			// matching `include`, not only the ones a test imported — reporting 90% of a tenth of the
			// codebase is the one number coverage exists to stop people quoting. The Svelte components
			// are largely untested and the figure should say so.
			include: ['src/**/*.{ts,svelte}', 'scripts/**/*.ts'],
			exclude: [
				// Generated by `specta` from the Rust commands — a diff here is a Rust change, and
				// holding generated code to a coverage target measures the generator.
				'src/lib/ipc/bindings.ts',
				'**/*.test.ts',
				'src/main.ts',
				'src/vite-env.d.ts'
			]
		}
	},

	// **Svelte's browser build under test, not its server one.** A component rendered from the SSR
	// build has no lifecycle — `lifecycle_function_unavailable` — because there is no client to run
	// it on. Guarded on `VITEST` so the dev server and the production build resolve as they did.
	resolve: process.env.VITEST ? { conditions: ['browser'] } : undefined,

	// Everything is bundled at build time — no Node runtime ships (Q5).
	build: {
		target: 'es2022',
		sourcemap: true,
		// MapLibre alone is ~800 kB. Code-splitting a desktop app that loads from disk buys nothing,
		// so the default 500 kB advisory is noise rather than a signal.
		chunkSizeWarningLimit: 1500
	}
});
