//! Turning a project into the commands that reproduce it elsewhere (C7, S5.5).
//!
//! **The desktop-to-production step.** Everything Studio does is something the CLI can do: a graph
//! is a `.vpl` that `versatiles convert` runs, a project is a directory `versatiles serve` can be
//! pointed at. What is missing is not capability but the exact invocation, and that is what someone
//! stares at when they want to put a map on a server.
//!
//! **Derived, never stored.** These are generated from the project as it is, so they cannot go stale
//! — a file written once and kept would describe the graphs a project used to have. [Q6] says the
//! same about the serve config for a different reason: `project.yaml` cannot double as one, because
//! `versatiles`' config sets `deny_unknown_fields` and any Studio key invalidates it.
//!
//! Only text is produced here. Whether it is shown, copied or written to disk is the caller's, and
//! nothing in this module touches a file.
//!
//! [Q6]: ../../docs/decisions.md

/// The command that turns one graph into a container.
///
/// Relative paths, because they are relative to the project directory the command is run in — the
/// same resolution `versatiles convert` and a `.vpl`'s own `filename=` already use.
#[must_use]
pub fn convert_command(graph: &str, target: &str) -> String {
	format!("versatiles convert {graph}.vpl {target}")
}

/// A `versatiles serve` config listing every graph as a source.
///
/// The name is the graph's — which is already its mount, its source name in the style and its
/// filename ([Q32](../../docs/decisions.md)), so a style written beside this needs no translation.
///
/// **Written as `name`/`src` rather than as the two-element `["name", "file"]` pair** that the
/// config module's own documentation shows: that form is refused by the parser those docs sit on
/// (`invalid type: sequence, expected struct TileSourceConfigHelper`). The test below feeds this to
/// the real `Config::from_string`, which is the only way to know — and is how the discrepancy was
/// found rather than shipped.
#[must_use]
pub fn serve_config(graphs: &[String]) -> String {
	let mut out = String::from(
		"# Generated by VersaTiles Studio. Run with:\n\
		 #   versatiles serve --config serve.yaml\n\
		 tiles:\n",
	);
	for graph in graphs {
		// Quoted, because a graph called `no` is a boolean to YAML and one called `2024` is a number.
		out.push_str(&format!("  - name: {graph:?}\n    src: \"{graph}.vpl\"\n"));
	}
	out
}

/// A container image that serves the project.
///
/// Deliberately thin: it copies the project in and runs the same command a person would. Anything
/// cleverer — building tiles at image-build time, multi-stage anything — is a decision about someone
/// else's deployment, and a Dockerfile is read before it is run.
#[must_use]
pub fn dockerfile(graphs: &[String]) -> String {
	let sources = graphs
		.iter()
		.map(|graph| format!("{graph}.vpl"))
		.collect::<Vec<_>>()
		.join(" ");
	format!(
		"# Generated by VersaTiles Studio.\n\
		 #\n\
		 # The pipelines are run when the server starts, so the data they read has to be reachable\n\
		 # from inside the container — mount it, or convert to a container first and serve that.\n\
		 FROM versatiles/versatiles:latest\n\
		 WORKDIR /data\n\
		 COPY serve.yaml {sources} ./\n\
		 EXPOSE 8080\n\
		 CMD [\"versatiles\", \"serve\", \"--config\", \"serve.yaml\", \"--ip\", \"0.0.0.0\"]\n"
	)
}

/// A workflow that rebuilds the tiles when the pipelines change.
///
/// One job, no caching, no deploy step: where the result goes is the one part of this nobody else
/// can guess, and a workflow that invented an answer would be deleted rather than edited.
#[must_use]
pub fn github_action(graphs: &[String], target_extension: &str) -> String {
	let steps = graphs
		.iter()
		.map(|graph| {
			format!(
				"      - name: Build {graph}\n        run: versatiles convert {graph}.vpl {graph}.{target_extension}\n"
			)
		})
		.collect::<String>();

	format!(
		"# Generated by VersaTiles Studio.\n\
		 name: Build tiles\n\
		 on:\n\
		 \x20 push:\n\
		 \x20   paths: ['**.vpl']\n\
		 \x20 workflow_dispatch:\n\
		 jobs:\n\
		 \x20 build:\n\
		 \x20   runs-on: ubuntu-latest\n\
		 \x20   steps:\n\
		 \x20     - uses: actions/checkout@v4\n\
		 \x20     - name: Install VersaTiles\n\
		 \x20       run: curl -sSfL https://github.com/versatiles-org/versatiles-rs/raw/main/scripts/install-unix.sh | sudo sh\n\
		 {steps}\
		 \x20     - uses: actions/upload-artifact@v4\n\
		 \x20       with:\n\
		 \x20         name: tiles\n\
		 \x20         path: '*.{target_extension}'\n"
	)
}

#[cfg(test)]
mod tests {
	use super::*;

	fn graphs() -> Vec<String> {
		vec!["basemap".to_string(), "hillshade".to_string()]
	}

	/// The point of C7 is that the generated config is one `versatiles serve` actually accepts —
	/// not something that looks like one. Parsed by the real parser rather than eyeballed.
	#[test]
	fn the_serve_config_is_one_versatiles_accepts() {
		let text = serve_config(&graphs());
		let config = versatiles::config::Config::from_string(&text)
			.unwrap_or_else(|error| panic!("versatiles refused its own config:\n{text}\n{error:#}"));

		let named: Vec<String> = config
			.tile_sources
			.iter()
			.filter_map(|entry| entry.name.clone())
			.collect();
		assert_eq!(named, graphs(), "every graph should be a source");
	}

	/// A project with no graphs still has to produce a config that parses, or "export" fails at the
	/// one moment someone is trying to get out of the application.
	#[test]
	fn an_empty_project_still_produces_a_valid_config() {
		let text = serve_config(&[]);
		assert!(versatiles::config::Config::from_string(&text).is_ok(), "{text}");
	}

	/// A graph name reaches YAML, and YAML has opinions about strings that look like other things.
	#[test]
	fn a_name_that_yaml_would_misread_is_quoted() {
		let text = serve_config(&["no".to_string(), "2024".to_string()]);
		let config = versatiles::config::Config::from_string(&text).unwrap_or_else(|e| panic!("{text}\n{e:#}"));
		let named: Vec<String> = config
			.tile_sources
			.iter()
			.filter_map(|entry| entry.name.clone())
			.collect();
		assert_eq!(
			named,
			["no", "2024"],
			"`no` is not a boolean and `2024` is not a number here"
		);
	}

	#[test]
	fn the_command_names_the_file_the_graph_is_saved_as() {
		assert_eq!(
			convert_command("basemap", "basemap.versatiles"),
			"versatiles convert basemap.vpl basemap.versatiles"
		);
	}

	/// Both generated files run the same command a person would, and both say where they came from.
	#[test]
	fn the_generated_files_explain_themselves() {
		for text in [
			serve_config(&graphs()),
			dockerfile(&graphs()),
			github_action(&graphs(), "versatiles"),
		] {
			assert!(text.starts_with('#'), "should say it was generated:\n{text}");
		}
	}

	#[test]
	fn the_dockerfile_carries_every_pipeline_it_serves() {
		let text = dockerfile(&graphs());
		assert!(text.contains("basemap.vpl hillshade.vpl"), "{text}");
		// Exec form, so the arguments are separate strings — which is also what stops a shell from
		// being involved in a container someone else runs.
		assert!(text.contains(r#""--config", "serve.yaml""#), "{text}");
		// Bound to all interfaces, or the published port reaches nothing.
		assert!(text.contains(r#""--ip", "0.0.0.0""#), "{text}");
	}

	#[test]
	fn the_workflow_builds_each_graph() {
		let text = github_action(&graphs(), "versatiles");
		assert!(
			text.contains("versatiles convert basemap.vpl basemap.versatiles"),
			"{text}"
		);
		assert!(
			text.contains("versatiles convert hillshade.vpl hillshade.versatiles"),
			"{text}"
		);
		// It runs when a pipeline changes, which is the only thing it can know about this project.
		assert!(text.contains("'**.vpl'"), "{text}");
	}
}
