/**
 * A recipe as `@versatiles/style` code (S4.6, D8).
 *
 * **This is what the recipe is for.** [Q36] keeps a preset, its adjustments and the layers someone
 * changed, rather than the 125 kB style they render to — and the reason given there was that a
 * design storing only the output could emit `style.json` and never the code. This is that half.
 *
 * The output is meant to be read as much as run: someone taking a style out of Studio and into a
 * build wants to see which preset it started from and what was done to it, not a wall of layers.
 *
 * [Q36]: ../../../docs/decisions.md
 */

import type { StyleSpecification } from 'maplibre-gl';
import type { Recipe } from '../ipc/commands';

/**
 * Where an exported style says its tiles are.
 *
 * **Not where Studio's are.** The map reads them from `studio://127.0.0.1:<an ephemeral port>`,
 * which is a URL that stops existing when the window closes — writing it into a file someone is
 * taking away would be a style that works exactly once, on one machine, until it does not. A
 * placeholder is a thing to replace; a dead localhost URL is a thing to debug.
 */
export const TILE_URL_PLACEHOLDER = 'https://example.org/tiles/{z}/{x}/{y}';

/** The style with its tile URLs replaced by something a reader is meant to change. */
export function forExport(style: StyleSpecification): StyleSpecification {
	const copy = structuredClone(style) as StyleSpecification;
	for (const source of Object.values(copy.sources ?? {})) {
		if ('tiles' in source && Array.isArray(source.tiles)) source.tiles = [TILE_URL_PLACEHOLDER];
	}
	return copy;
}

/** A preset with no builder behind it cannot be written as a builder call. */
export function canGenerateCode(recipe: Recipe): boolean {
	return recipe.preset !== 'derived';
}

/**
 * The code for a recipe, or `null` when there is none to write.
 *
 * `derived` has no `@versatiles/style` builder — it is assembled from whatever layers the tiles
 * turned out to have (S4.4), so there is nothing to name in an import. Those export as `style.json`,
 * which is the honest form for a style that has no shorter description than itself.
 */
export function styleCode(recipe: Recipe): string | null {
	if (!canGenerateCode(recipe)) return null;

	const options: string[] = [`\ttiles: ['${TILE_URL_PLACEHOLDER}']`];
	const recolor = Object.entries(recipe.recolor).filter(([, value]) => value !== undefined && value !== null);
	if (recolor.length > 0) {
		options.push(
			`\trecolor: {\n${recolor.map(([key, value]) => `\t\t${key}: ${JSON.stringify(value)}`).join(',\n')}\n\t}`
		);
	}

	const lines = [
		'// Generated by VersaTiles Studio. Point `tiles` at where yours are published.',
		`import { ${recipe.preset} } from '@versatiles/style';`,
		'',
		`const style = ${recipe.preset}({`,
		options.join(',\n'),
		'});'
	];

	const overrides = Object.entries(recipe.overrides);
	if (overrides.length > 0) {
		// Applied as a loop over the built style rather than folded into the call: these are changes
		// to *layers*, and the builder takes no argument for them. Written out so the file runs
		// as-is, which is the difference between code and a description of code.
		lines.push(
			'',
			'// Layer changes made in Studio.',
			`const overrides: Record<string, { visible?: boolean; minZoom?: number; maxZoom?: number; paint?: object }> = ${JSON.stringify(
				Object.fromEntries(overrides.map(([id, patch]) => [id, clean(patch)])),
				null,
				'\t'
			)};`,
			'',
			'for (const layer of style.layers) {',
			'\tconst patch = overrides[layer.id];',
			'\tif (!patch) continue;',
			"\tif (patch.visible === false) layer.layout = { ...layer.layout, visibility: 'none' };",
			'\tif (patch.minZoom !== undefined) layer.minzoom = patch.minZoom;',
			'\tif (patch.maxZoom !== undefined) layer.maxzoom = patch.maxZoom;',
			'\tif (patch.paint) layer.paint = { ...layer.paint, ...patch.paint };',
			'}'
		);
	}

	lines.push('', 'export default style;', '');
	return lines.join('\n');
}

/** Drops the keys a patch left unset, so the emitted object says only what was changed. */
function clean(patch: object): object {
	return Object.fromEntries(Object.entries(patch).filter(([, value]) => value !== undefined && value !== null));
}
