// Generated from the Rust commands by `cargo test -p versatiles-studio` — do not edit.
//
// Hand-written wrappers and the reasoning behind each command live in `commands.ts`, which
// re-exports everything here. See src-tauri/src/bindings.rs.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Smoke-test command proving the IPC boundary is wired. */
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
	/**
	 *  Base URL of the embedded server, for MapLibre to fetch tiles from.
	 * 
	 *  The webview learns the port this way rather than assuming one, because the server binds an
	 *  ephemeral port (see `studio_core::server`).
	 */
	serverBaseUrl: () => typedError<string, string>(__TAURI_INVOKE("server_base_url")),
	/**
	 *  Opens another window. One window per project ([Q16]) — this is what ⌘N does.
	 * 
	 *  Each window gets its own webview process, so a crash takes one project down rather than all of
	 *  them. The label must be unique; the caller owns that.
	 * 
	 *  [Q16]: ../../docs/decisions.md
	 */
	openWindow: (label: string) => typedError<null, string>(__TAURI_INVOKE("open_window", { label })),
	/**
	 *  Enables or disables the menu items that need something to be open (S0.1).
	 * 
	 *  **Pushed down, not pulled up.** Whether there is a project to save is a `$derived` in the
	 *  webview, and a native menu cannot read one — so the window tells the menu when the answer
	 *  changes. One flag, because one flag is what the menu actually varies on; anything finer would be
	 *  a mechanism built for a second caller that does not exist.
	 */
	setMenuState: (hasProject: boolean) => typedError<null, string>(__TAURI_INVOKE("set_menu_state", { hasProject })),
	/**  Everything that has gone wrong this session, oldest first. */
	diagnostics: () => typedError<Problem[], string>(__TAURI_INVOKE("diagnostics")),
	/**
	 *  What the run before this one left behind — the half a crash does not get to erase.
	 * 
	 *  **Read from the file, not from memory**, because there is no memory left: the session this
	 *  describes is the one that was killed, ran out of memory, or aborted on a panic. Read on demand
	 *  rather than at startup, since most launches follow an ordinary one and nobody opens the tab.
	 * 
	 *  Empty is the ordinary answer — a first launch, or a log directory that could not be written.
	 */
	previousProblems: () => typedError<Problem[], string>(__TAURI_INVOKE("previous_problems")),
	/**
	 *  Records a problem the webview saw, and answers how many there now are.
	 * 
	 *  **The count comes back** so the bar's badge is a fact rather than a tally the window keeps: a
	 *  reload, a second window and the core's own entries all have to agree on one number, and only the
	 *  core can see all three.
	 */
	logDiagnostic: (report: NewProblem) => typedError<number, string>(__TAURI_INVOKE("log_diagnostic", { report })),
	/**  Forgets them all — for reproducing a problem cleanly before copying the report. */
	clearDiagnostics: () => typedError<null, string>(__TAURI_INVOKE("clear_diagnostics")),
	/**
	 *  Writes a problem report where the user asked for it.
	 * 
	 *  **The webview composes the text**, for the same reason `export_style` takes its contents: what a
	 *  report says is a presentation decision, and the half of it that only the window can answer —
	 *  the engine, the GPU — never crosses into the core at all.
	 * 
	 *  The path came from a native save dialog, which is the whole of the trust story.
	 */
	saveReport: (path: string, text: string) => typedError<null, string>(__TAURI_INVOKE("save_report", { path, text })),
	/**  The same, for the panel's footer — the path is written there, and a path you can open is better. */
	showLog: () => typedError<null, string>(__TAURI_INVOKE("show_log")),
	environment: () => typedError<Environment, string>(__TAURI_INVOKE("environment")),
	/**
	 *  Starts an export and returns the job running it.
	 * 
	 *  **Returns the job rather than the result.** A conversion is the long operation the runner exists
	 *  for (E7) — minutes and gigabytes — so waiting for it here would hold a command open for the whole
	 *  write and leave the webview with nothing to show meanwhile. The job's progress, log and failure
	 *  all arrive on the event channel the bar is already listening to, which is where a user can watch
	 *  or cancel it.
	 * 
	 *  **`Queued`, not `Latest`** ([Q27]): two conversions compete for the same disk and cores and
	 *  finish later than the same two in sequence, and a second export is a second thing you asked for
	 *  rather than a correction of the first — unlike a preview, which stops mattering the moment the
	 *  pipeline changes.
	 * 
	 *  [Q27]: ../../../docs/decisions.md
	 */
	exportGraph: (graph: number, target: string, bounds: Bounds) => typedError<number, string>(__TAURI_INVOKE("export_graph", { graph, target, bounds })),
	/**
	 *  What an export would cost, before one is started (S3.7, C6).
	 * 
	 *  **Awaited rather than run as a job**, unlike [`export_graph`]. A job is the right shape for
	 *  something you start and walk away from; this is something a dialog is waiting on, and it is
	 *  bounded by [`studio_core::estimate::BUDGET`] precisely so that waiting is reasonable. Putting a
	 *  two-second measurement in the status bar would also announce it to a window that is not asking —
	 *  the bar is for work the user started.
	 * 
	 *  **The refusals are the same as the export's**, and arrive here first: an absurd pyramid and a
	 *  bounding box that is inside out are both things the dialog can say next to the field that causes
	 *  them, rather than after a filename has been chosen.
	 */
	estimateExport: (graph: number, bounds: Bounds) => typedError<Estimate, string>(__TAURI_INVOKE("estimate_export", { graph, bounds })),
	/**
	 *  Narrows what an export of this graph writes (F2, S5.2, S5.4).
	 * 
	 *  **Kept on the graph rather than in the export dialog.** A crop is arrived at by looking at the
	 *  map — dragging a rectangle over the city you mean — and the dialog is a modal that covers it. It
	 *  is also worth keeping: it goes into the project manifest, so reopening a project tomorrow is
	 *  still about the same place.
	 * 
	 *  The estimate and the write both narrow to it, so what the pane shows and what lands on disk
	 *  cannot be about different tiles.
	 */
	setCrop: (graph: number, crop: Bounds) => typedError<null, string>(__TAURI_INVOKE("set_crop", { graph, crop })),
	/**
	 *  The container formats Studio can write.
	 * 
	 *  Asked for rather than repeated in the webview: the list decides the file dialog's filters, the
	 *  modal's wording *and* whether a chosen path is refused, and three copies of it would disagree
	 *  the first time a format was added.
	 */
	writableFormats: () => __TAURI_INVOKE<string[]>("writable_formats"),
	/**
	 *  Points the runner's events at this window, and returns what it has missed.
	 * 
	 *  **Called once, at startup, and again after every reload.** The channel belongs to a webview, and
	 *  a reload gets a new one; jobs started before it keep running, which is the whole reason a
	 *  conversion is not tied to the window that asked for it. Returning the list in the same call is
	 *  what closes the gap — subscribing and then listing separately leaves a window where an event
	 *  lands between the two and is counted twice, or lands before the list is taken and is missed.
	 * 
	 *  **This window's work, not the machine's** ([S7.3](../../../docs/scope-release-3.md)): one runner
	 *  still, but a list per project, so an export started next door does not appear in this bar.
	 */
	subscribeJobs: (channel: Channel<JobEvent>) => typedError<Job[], string>(__TAURI_INVOKE("subscribe_jobs", { channel })),
	/**  One job's log, oldest line first. Fetched when a row is expanded, not streamed on connect. */
	jobLog: (id: number) => typedError<string[], string>(__TAURI_INVOKE("job_log", { id })),
	/**  Asks a job to stop. Idempotent — a job that has already ended stays ended. */
	cancelJob: (id: number) => typedError<null, string>(__TAURI_INVOKE("cancel_job", { id })),
	/**
	 *  Opens a container, mounts it on the embedded server, and returns what is cheap to know.
	 * 
	 *  Deliberately does **not** touch the window's pipeline. Opening a file from the dialog should set
	 *  it; mounting a container because the pipeline already mentions it should not, or following an
	 *  edit would overwrite the edit. The caller knows which it is doing; the `vpl` field is here so it
	 *  can set the pipeline itself.
	 * 
	 *  The mount name is derived from the path so the webview can build tile URLs without a second
	 *  round trip. Re-opening the same path replaces the mount rather than stacking duplicates — see
	 *  [`ServerManager::mount`](studio_core::server::ServerManager::mount), which is where that is
	 *  actually enforced.
	 */
	openContainer: (source: string) => typedError<OpenedContainer, string>(__TAURI_INVOKE("open_container", { source })),
	/**  The recently opened sources, newest first (A7). */
	recentSources: () => typedError<RecentEntry[], string>(__TAURI_INVOKE("recent_sources")),
	/**  Drops one entry — for a path that has gone away, or that the user wants gone. */
	forgetRecent: (source: string) => typedError<null, string>(__TAURI_INVOKE("forget_recent", { source })),
	/**
	 *  Decodes one tile of an open container, layer by layer (A4).
	 * 
	 *  Takes the source string rather than the mount name so the webview never has to track both.
	 */
	inspectTile: (source: string, z: number, x: number, y: number) => typedError<{
	z: number,
	x: number,
	y: number,
	/**  Bytes as stored in the container, before decompression. */
	storedBytes: number,
	layers: LayerInspection[],
} | null, string>(__TAURI_INVOKE("inspect_tile", { source, z, x, y })),
	listViews: () => typedError<View[], string>(__TAURI_INVOKE("list_views")),
	/**  Saves a view, replacing any of the same name. */
	saveView: (view: View) => typedError<null, string>(__TAURI_INVOKE("save_view", { view })),
	deleteView: (name: string) => typedError<boolean, string>(__TAURI_INVOKE("delete_view", { name })),
	/**
	 *  Puts the views in the order given, and returns what that came to.
	 * 
	 *  Returns the list rather than nothing because the core has the last word on it — a name the
	 *  caller does not hold is ignored, and one it left out keeps its place — so the webview renders
	 *  what was actually stored instead of what it hoped had been.
	 */
	reorderViews: (order: string[]) => typedError<View[], string>(__TAURI_INVOKE("reorder_views", { order })),
	/**  The recipe as it stands. */
	style: () => typedError<Recipe_Serialize, string>(__TAURI_INVOKE("style")),
	/**  Switches which style a source starts from (D1). */
	setStylePreset: (graph: number, preset: Preset) => typedError<Recipe_Serialize, string>(__TAURI_INVOKE("set_style_preset", { graph, preset })),
	/**
	 *  Corrects what a source's tiles are being read as (S6.1).
	 * 
	 *  `None` hands the question back to the webview's own reading. Changing the kind across the
	 *  vector/raster line replaces the appearance, because the old one describes something this source
	 *  is no longer being drawn as — and keeping it would mean a recipe carrying two answers again,
	 *  which is what S6.4 removed.
	 */
	setStyleKind: (graph: number, kind: 
/**  Vector tiles using Shortbread's layer names, which the six presets are written against. */
"vectorShortbread" | 
/**  Vector tiles of anything else. Styled from the layers actually present (D2). */
"vectorOther" | 
/**  Raster tiles meant to be looked at — imagery, a scan, a rendered map (D11). */
"rasterImage" | 
/**
 *  Raster tiles encoding elevation, to be drawn as hillshade rather than as colour (D12).
 * 
 *  The encoding — `mapbox`, `terrarium`, `versatiles` — is deliberately not carried here yet.
 *  Nothing draws a DEM until S6.6, and that is the step that has to decide whether the encoding
 *  belongs on this enum or is re-read from `tile_schema` at the point of use.
 */
"rasterDem" | null) => typedError<Recipe_Serialize, string>(__TAURI_INVOKE("set_style_kind", { graph, kind })),
	/**
	 *  Sets the raster adjustment — the imagery equivalent of `set_style_recolor` (S6.3, D11).
	 * 
	 *  Whole-struct for the same reason that one is: the controls move together, and one command per
	 *  field would let the two ends disagree about which of them the recipe currently has. Called when
	 *  a gesture ends, so a drag is one undo entry rather than sixty.
	 */
	setStyleRaster: (graph: number, raster: RasterAdjust_Deserialize) => typedError<Recipe_Serialize, string>(__TAURI_INVOKE("set_style_raster", { graph, raster })),
	/**
	 *  Sets the draw order, bottom first ([S6.5](../../../docs/scope-release-2.md)).
	 * 
	 *  The whole list, not a move: a reorder is one gesture with one result, and "move this one up"
	 *  would need the two ends to agree about what the list was before it — which is the disagreement
	 *  `set_style_recolor` avoids the same way.
	 * 
	 *  Names that no graph has are kept rather than filtered. `Recipe::draw_order` ignores them, and
	 *  dropping them here would lose a position for a graph that is only temporarily absent.
	 */
	setStyleOrder: (order: string[]) => typedError<Recipe_Serialize, string>(__TAURI_INVOKE("set_style_order", { order })),
	/**
	 *  Sets the hillshade settings for an elevation source ([S6.6](../../../docs/scope-release-2.md), D12).
	 * 
	 *  Whole-struct, like the recolour and the raster adjustment above, and for the same reason.
	 */
	setStyleHillshade: (graph: number, shade: Hillshade_Deserialize) => typedError<Recipe_Serialize, string>(__TAURI_INVOKE("set_style_hillshade", { graph, shade })),
	/**
	 *  Drops a source's overrides for layers its style no longer has ([S6.7](../../../docs/scope-release-2.md)).
	 * 
	 *  `present` is the ids the rendered style actually contains, which only the webview knows —
	 *  `@versatiles/style` renders there ([Q36]), so the core cannot work out what a preset produced.
	 * 
	 *  Returns the recipe, and the count goes to the pane through the difference it can see. Deliberate
	 *  rather than automatic: an override that has gone quiet under one preset comes back under another,
	 *  and clearing them on a switch would delete work someone was in the middle of comparing.
	 */
	pruneStyleOverrides: (graph: number, present: string[]) => typedError<Recipe_Serialize, string>(__TAURI_INVOKE("prune_style_overrides", { graph, present })),
	/**
	 *  Sets the global recolouring — hue, saturation, brightness, contrast and the rest (D1, D5).
	 * 
	 *  Takes the whole of it rather than one field at a time. The controls move together, the webview
	 *  holds them together, and ten commands would let the two ends disagree about which of them the
	 *  recipe currently has.
	 */
	setStyleRecolor: (graph: number, recolor: Recolor_Deserialize) => typedError<Recipe_Serialize, string>(__TAURI_INVOKE("set_style_recolor", { graph, recolor })),
	/**  Changes one layer of a vector source (D3, S4.5). */
	setLayerOverride: (graph: number, layer: string, patch: LayerOverride_Deserialize) => typedError<Recipe_Serialize, string>(__TAURI_INVOKE("set_layer_override", { graph, layer, patch })),
	/**
	 *  Writes a style someone chose a destination for (S4.6, D8).
	 * 
	 *  **The webview supplies the text.** A style is rendered by `@versatiles/style`, which is a
	 *  JavaScript library, and the recipe exists precisely so that the core never has to hold the 125 kB
	 *  it produces ([Q36]). So this command is about the destination rather than the contents: it checks
	 *  the extension and writes atomically, the way a `.vpl` is saved.
	 * 
	 *  The path came from a native save dialog, which is the whole of the trust story — see
	 *  [architecture.md](../../../docs/architecture.md)'s note on paths across the control plane.
	 */
	exportStyle: (path: string, contents: string) => typedError<null, string>(__TAURI_INVOKE("export_style", { path, contents })),
	/**
	 *  Writes a style bundle: the style, the glyphs it names and the sprite sheet (D8, S4.6).
	 * 
	 *  **The webview supplies the style text and the font list**, for the same reason `export_style`
	 *  above takes its contents: `@versatiles/style` renders in JavaScript, and the fonts a style uses
	 *  are read out of what it rendered to.
	 * 
	 *  The archives come from here, because only the app knows where a bundled resource lives — beside
	 *  the binary when packaged, in the source tree in dev — and where installed families were put.
	 *  Installed families are searched *after* the bundled tier, mirroring the mount order: the Latin
	 *  subset answers first, and anything else is found in whichever family archive has it.
	 * 
	 *  Returns the fonts nothing had, which the pane says out loud rather than swallowing.
	 * 
	 *  **On a blocking thread**: this reads two tar archives and writes a few hundred files.
	 */
	exportStyleBundle: (target: string, zip: boolean, contents: string, fonts: string[]) => typedError<string[], string>(__TAURI_INVOKE("export_style_bundle", { target, zip, contents, fonts })),
	/**  What Studio can write a style as/// What Studio can write a style as — the file dialog's filters come from here. */
	styleFormats: () => __TAURI_INVOKE<string[]>("style_formats"),
	/**
	 *  Writes every graph, the style recipe, and the rendered style.
	 * 
	 *  **The rendered style comes from the webview**, for the reason [Q36] gives: the generator is
	 *  `@versatiles/style` and the core holds the recipe rather than the 125 kB it produces. `None` when
	 *  there is nothing on the map yet, which is a project saved before it draws anything rather than an
	 *  error.
	 * 
	 *  Saving also moves what relative paths resolve against, because they are now relative to this
	 *  directory — a `.vpl` reading `berlin.mbtiles` beside it must keep meaning that file.
	 * 
	 *  [Q36]: ../../../docs/decisions.md
	 */
	saveProject: (dir: string, style: string | null) => typedError<null, string>(__TAURI_INVOKE("save_project", { dir, style })),
	/**
	 *  Opens a project directory, replacing everything currently open.
	 * 
	 *  **Replacing, not merging.** A window is one project ([Q16]); opening a second one beside the
	 *  first would leave two sets of graphs sharing an undo stack and a style, which is not a project.
	 * 
	 *  Returns the recipe, because the webview has to render the style again — the manifest carries what
	 *  it is made from, not the style itself.
	 * 
	 *  [Q16]: ../../../docs/decisions.md
	 */
	openProject: (dir: string) => typedError<Recipe_Serialize, string>(__TAURI_INVOKE("open_project", { dir })),
	/**  Whether a directory holds a project — so the open dialog can say why one does not. */
	isProject: (dir: string) => __TAURI_INVOKE<boolean>("is_project", { dir }),
	/**
	 *  Where this project lives, or `None` if it has never been saved or opened.
	 * 
	 *  What tells "Save Project" from "Save Project As…": with an answer here the first writes without
	 *  asking, and without one there is nothing to write to yet and it has to ask like the second.
	 */
	projectPath: () => typedError<string | null, string>(__TAURI_INVOKE("project_path")),
	/**
	 *  What copying this project elsewhere would carry, without writing anything.
	 * 
	 *  Asked before the destination is chosen, so the dialog can say what it costs — the same
	 *  plan-then-write split `estimate` and `export` use.
	 */
	copyPlan: () => typedError<CopyPlan, string>(__TAURI_INVOKE("copy_plan")),
	/**
	 *  Writes a self-contained copy — a directory, or one `.zip`.
	 * 
	 *  **Planned again here rather than carried over from [`copy_plan`].** The plan is a few `stat`
	 *  calls, and recomputing it means what is written describes the project as it is now rather than as
	 *  it was when a dialog opened.
	 * 
	 *  **On a blocking thread**, because this copies tile containers: `std::fs::copy` of twenty
	 *  gigabytes must not be sitting on the async runtime. There is no progress to report — neither
	 *  `fs::copy` nor the zip writer offers any — so the status bar says it is working and that is all
	 *  it can honestly say.
	 */
	saveProjectCopy: (target: string, zip: boolean, style: string | null) => typedError<null, string>(__TAURI_INVOKE("save_project_copy", { target, zip, style })),
	/**  Every family this build offers, and whether it is installed. */
	fontFamilies: () => typedError<Family[], string>(__TAURI_INVOKE("font_families")),
	/**
	 *  Downloads a family and mounts it, as a job.
	 * 
	 *  **`Queued`, like an export** ([Q27]): 48 MB is minutes on a slow line, it is something you start
	 *  and walk away from, and two at once would only make both slower. Returning the job rather than
	 *  the result is what lets the bar show progress and offer to cancel.
	 * 
	 *  The mount happens here rather than at the next start, because a font someone just installed and
	 *  cannot use until they restart is a font they will think failed to install.
	 * 
	 *  [Q27]: ../../../docs/decisions.md
	 */
	installFont: (id: string) => typedError<number, string>(__TAURI_INVOKE("install_font", { id })),
	/**
	 *  Removes a family. Reports whether one was there.
	 * 
	 *  **The mount is not removed**, and cannot be: the server takes static sources and never gives them
	 *  back. Until it does, a family removed mid-session keeps serving until the next start — which is
	 *  the harmless direction for this to be wrong in, and is said here rather than left to be noticed.
	 */
	removeFont: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("remove_font", { id })),
	/**  The remembered pane layout, or the default one. */
	layout: () => typedError<Layout, string>(__TAURI_INVOKE("layout")),
	/**
	 *  Records the layout after the user collapses a section or drags the pane edge.
	 * 
	 *  A failed write is logged and swallowed, the same as recents: a pane width is not worth
	 *  interrupting someone's work over, and the next change will try again anyway.
	 */
	setLayout: (layout: Layout) => typedError<Layout, string>(__TAURI_INVOKE("set_layout", { layout })),
	/**  Parses VPL into a tree with spans, so the webview can render one field per property. */
	vplParse: (text: string) => typedError<Pipeline, VplError>(__TAURI_INVOKE("vpl_parse", { text })),
	/**
	 *  Sets the value at `span` and returns the whole document back.
	 * 
	 *  Returning the text rather than a patch keeps the webview from having to apply spans itself; it
	 *  re-parses what it gets and re-renders. The documents here are a few hundred bytes.
	 */
	vplSetValue: (text: string, span: Span, value: string) => typedError<string, VplError>(__TAURI_INVOKE("vpl_set_value", { text, span, value })),
	/**
	 *  Sets a parameter on the node whose *name* occupies `span`, adding it if it is not set.
	 * 
	 *  Takes the node rather than the property, because the generated form offers every parameter an
	 *  operation accepts — including the ones the node has no span for yet.
	 */
	vplSetProperty: (text: string, span: Span, key: string, values: string[]) => typedError<string, VplError>(__TAURI_INVOKE("vpl_set_property", { text, span, key, values })),
	/**  Removes the property at `span`. This is what clearing a field means (see `NodeCard`). */
	vplRemoveProperty: (text: string, span: Span) => typedError<string, VplError>(__TAURI_INVOKE("vpl_remove_property", { text, span })),
	/**
	 *  Adds an operation to the chain, immediately after the node whose name occupies `span`.
	 * 
	 *  The pipeline could only gain a transform by typing VPL before this; the graph could add a source
	 *  and nothing else. Which operations exist comes from [`vpl_operations`], so a new one upstream is
	 *  offerable without a change here (C2).
	 */
	vplInsertNode: (text: string, span: Span, operation: string) => typedError<string, VplError>(__TAURI_INVOKE("vpl_insert_node", { text, span, operation })),
	/**
	 *  Removes the node whose name occupies `span`, and the separator that joined it to the chain.
	 * 
	 *  Refused when it would empty the pipeline — see `Document::remove_node` for why that is a message
	 *  rather than a parse failure.
	 */
	vplRemoveNode: (text: string, span: Span) => typedError<string, VplError>(__TAURI_INVOKE("vpl_remove_node", { text, span })),
	vplReview: (text: string) => typedError<Review, VplError>(__TAURI_INVOKE("vpl_review", { text })),
	/**
	 *  Every operation and its parameters, for the generated forms (C2, S2.6).
	 * 
	 *  Fetched once and cached by the caller: this is build-time information about the binary, so it
	 *  cannot change while Studio is running.
	 */
	vplOperations: () => __TAURI_INVOKE<OperationInfo[]>("vpl_operations"),
	/**
	 *  Every way this build can bring data in (S3.2).
	 * 
	 *  Build-time information about the binary, like [`vpl_operations`] — the catalogue is derived from
	 *  the operation registry, so it cannot offer something this build cannot do.
	 */
	importKinds: () => __TAURI_INVOKE<ImportKind[]>("import_kinds"),
	/**
	 *  Which kind a path belongs to, or `None` for a file Studio has no way in for.
	 * 
	 *  Asked here rather than matched in the webview so that one list of extensions serves the dialog,
	 *  the drop target and the cards — three places that had already started to disagree.
	 */
	importKindFor: (path: string) => __TAURI_INVOKE<{
	/**  Stable identifier, used by the caller to say which card was chosen. */
	id: string,
	/**  What the card says. */
	label: string,
	/**  The one-line explanation under it. */
	detail: string,
	/**  Extensions for the file dialog and the drop filter, without the dot, lowercase. */
	extensions: string[],
	/**
	 *  The read operation a chosen file becomes.
	 * 
	 *  `None` for a `.vpl`, which is not a node — it is a whole document, and opening one replaces
	 *  the pipeline rather than adding to it (C9).
	 */
	operation: string | null,
	/**
	 *  Required parameters a filename cannot supply, in the order the operation declares them.
	 * 
	 *  Empty means picking a file completes the import. Anything here has to come from somewhere
	 *  else: the file's own header, or the person.
	 */
	needs: string[],
} | null>("import_kind_for", { path }),
	/**
	 *  The read node a chosen file becomes — `from_geo filename='…'`, quoting included.
	 * 
	 *  The quoting is the core's, for the reason [`vpl_set_value`] gives: a second implementation of
	 *  VPL's quoting rules in TypeScript is exactly what would drift. So is the *filling in*: a CSV
	 *  arrives with its coordinate columns already set when its header names them unambiguously
	 *  (S3.4), which is the difference between an import that runs and one that opens a form.
	 */
	importReadNode: (kindId: string, path: string) => __TAURI_INVOKE<string>("import_read_node", { kindId, path }),
	/**
	 *  What every node's fields could be set to, read from what each node points at (S3.4).
	 * 
	 *  **The whole graph, not the selected node.** Every node in the chain carries its own form, so
	 *  every node needs its own answer — one `from_csv` reading `a.csv` has nothing to say about
	 *  another reading `b.csv`. It used to take a path, which was correct only while a single node had
	 *  a form to fill in.
	 * 
	 *  One call rather than one per node: `for_node` refuses anything that is not a `from_csv` before
	 *  it touches a disk, so the sweep costs a header read per CSV node and a string comparison for the
	 *  rest.
	 */
	fieldSuggestions: (graph: number) => typedError<NodeSuggestions[], string>(__TAURI_INVOKE("field_suggestions", { graph })),
	/**  Every graph in this project, in the order the pane shows them ([Q32]). */
	graphs: () => typedError<GraphInfo[], string>(__TAURI_INVOKE("graphs")),
	/**  One graph in full, or `None` if it has been removed. */
	graph: (id: number) => typedError<{
	/**
	 *  Which graph this is ([Q32](../../../docs/decisions.md)). The webview addresses everything by
	 *  id rather than by name, so a rename cannot invalidate a reference held mid-edit.
	 */
	graph: number,
	name: string,
	text: string,
	pipeline: Pipeline,
	/**  For the editor to paint, derived from the same tree ([Q25](../../../docs/decisions.md)). */
	tokens: Token[],
	/**  Checked against the operations that exist (C4). A pipeline can parse and still be wrong. */
	diagnostics: Diagnostic[],
	/**  Whether ⌘Z and ⇧⌘Z have anywhere to go, so the interface can say so. */
	canUndo: boolean,
	canRedo: boolean,
	/**  The `.vpl` this came from, if any, so Save has somewhere to write without asking. */
	path: string | null,
	/**  Whether the pipeline differs from what is on disk. */
	dirty: boolean,
} | null, string>(__TAURI_INVOKE("graph", { id })),
	/**
	 *  Creates a graph from VPL text, and returns it.
	 * 
	 *  Takes the **source** rather than a name, so the one rule that turns a file into a graph name
	 *  lives here and not in each caller ([Q35]) — a webview that passed a whole path would have named
	 *  a graph `users-me-data-berlin-mbtiles`. Two `places.geojson` files in different folders both want
	 *  to be `places`, and the second becoming `places-2` beats a refusal or a silent overwrite.
	 * 
	 *  `None` is for a graph with no file behind it, which nothing creates today.
	 */
	addGraph: (source: string | null, text: string) => typedError<DocumentView, VplError>(__TAURI_INVOKE("add_graph", { source, text })),
	/**  Removes a graph, and reports whether there was one. */
	removeGraph: (id: number) => typedError<boolean, string>(__TAURI_INVOKE("remove_graph", { id })),
	/**
	 *  Renames a graph, and reports the name it actually took.
	 * 
	 *  The name is the mount, the source name in `style.json` and the `.vpl` filename at once ([Q32]),
	 *  so this remounts under the new name — and since [S6.4](../../../docs/scope-release-2.md) the
	 *  recipe files each source's style under that name too, so the style moves with it.
	 * 
	 *  **Without this a rename silently resets the style.** The entry would stay under the old name,
	 *  referenced by nothing, and the source would come back with defaults as though it had never been
	 *  touched. It is not recorded as a style edit: renaming a graph is not a restyling, and ⌘Z after
	 *  one should undo the rename rather than half of it.
	 */
	renameGraph: (id: number, name: string) => typedError<string, string>(__TAURI_INVOKE("rename_graph", { id, name })),
	/**
	 *  Replaces a graph's text, rejecting what does not parse.
	 * 
	 *  The editor holds the text a user is typing, which is often mid-edit and invalid; the *document*
	 *  never is. A rejection carries a span so the editor can mark it (C4).
	 */
	setGraph: (id: number, text: string, kind: 
/**  A keystroke in the VPL editor. Consecutive ones merge. */
"typing" | 
/**
 *  A parameter form or the graph — a deliberate, discrete change. The default, because it is
 *  the conservative one: a caller that says nothing gets its own undo step.
 */
"structured" | 
/**  The document was replaced wholesale, e.g. by opening a file. */
"replaced" | null) => typedError<DocumentView, VplError>(__TAURI_INVOKE("set_graph", { id, text, kind })),
	/**
	 *  Lays a graph's VPL out again, keeping its comments ([vt#249], S1.11).
	 * 
	 *  **Recorded as an edit, not a rewrite.** It goes on the undo stack like anything else, and the
	 *  file behind it is kept — reformatting a `.vpl` is a change to it, not a replacement of it, so
	 *  Save still writes where it came from.
	 * 
	 *  [vt#249]: https://github.com/versatiles-org/versatiles-rs/issues/249
	 */
	formatGraph: (id: number) => typedError<DocumentView, VplError>(__TAURI_INVOKE("format_graph", { id })),
	/**
	 *  Runs the pipeline up to `path` and mounts the result — as a cancellable job (S2.7, S3.1).
	 * 
	 *  Building opens the inputs, which on a large source is not instant, so this runs in the runner's
	 *  [`Lane::Latest`]: **editing the pipeline again stops the build that is now out of date**, rather
	 *  than leaving it to finish an answer nobody will look at. That is also why the caller no longer
	 *  needs a token to discard stale replies — being superseded is something the runner knows, so it
	 *  is something this can report.
	 */
	previewPipeline: (graph: number, path: number[]) => typedError<PreviewOutcome, string>(__TAURI_INVOKE("preview_pipeline", { graph, path })),
	/**
	 *  Builds a graph in full and mounts it under its own name ([Q32]).
	 * 
	 *  Every graph is served, because that is what a style names — this is the ordinary view, and the
	 *  pin is the exception layered on top. Mounting by name rather than under one shared `preview`
	 *  mount is what lets a style reference `basemap` and `hillshade` separately.
	 */
	mountGraph: (graph: number) => typedError<{
	/**  Mount name, stable so a rebuild replaces rather than accumulates. */
	name: string,
	tileUrl: string,
	info: ContainerInfo,
	/**
	 *  The layers this produces, with their property keys (S3.3, E1).
	 * 
	 *  Carried on the preview rather than fetched separately because it is an answer about *this*
	 *  build: asking afterwards would race the next edit, and the form would offer property names
	 *  from a pipeline that no longer exists. Empty for raster output.
	 */
	layers: LayerInspection[],
	/**
	 *  Which transforms can be appended to this, and why the rest cannot (S2.14).
	 * 
	 *  Carried here for the same reason as `layers`, and it is the same kind of answer: what fits
	 *  depends on what this build produces, so asking separately would race the next edit and offer
	 *  operations chosen for a pipeline that no longer exists. It also costs nothing extra — the
	 *  source is already built and every check is a comparison against its declared tile type.
	 */
	fits: Fit[],
} | null, string>(__TAURI_INVOKE("mount_graph", { graph })),
	/**  Where the map is looking: the pinned node, or `None` for the ordinary state ([Q32]). */
	pinned: () => typedError<{
	graph: number,
	path: number[],
} | null, string>(__TAURI_INVOKE("pinned")),
	/**
	 *  Pins the map to one node, or clears the pin.
	 * 
	 *  **Exactly one across the project.** Pinning elsewhere moves it; pinning the pinned node clears
	 *  it, which is the gesture that gets you back to seeing everything.
	 */
	setPin: (pin: {
	graph: number,
	path: number[],
} | null) => typedError<{
	graph: number,
	path: number[],
} | null, string>(__TAURI_INVOKE("set_pin", { pin })),
	/**
	 *  Steps back, or forward again. `None` when there is nowhere to go.
	 * 
	 *  **One stack across every graph** ([Q32], G6), so this may hand back a graph other than the one
	 *  being edited — which is why it returns the whole document rather than just its text.
	 */
	undo: () => typedError<({ graph: DocumentView }) & { style?: never } | ({ style: Recipe_Serialize }) & { graph?: never } | null, VplError>(__TAURI_INVOKE("undo")),
	redo: () => typedError<({ graph: DocumentView }) & { style?: never } | ({ style: Recipe_Serialize }) & { graph?: never } | null, VplError>(__TAURI_INVOKE("redo")),
	/**
	 *  Opens a `.vpl` file as this window's pipeline (C9, S2.9).
	 * 
	 *  A pipeline written by hand or emitted by the CLI has to be openable, or "edit VPL" only ever
	 *  means "edit VPL Studio wrote" and the two tools cannot hand work to each other.
	 * 
	 *  **Relative paths in the file resolve against the file**, the way `versatiles convert` resolves
	 *  them — `from_container filename="berlin.mbtiles"` beside the `.vpl` means exactly that — so
	 *  opening one moves `project_dir`.
	 */
	openVpl: (path: string) => typedError<DocumentView, VplError>(__TAURI_INVOKE("open_vpl", { path })),
	/**
	 *  Writes the pipeline to a `.vpl` file and remembers it as the file this window is editing.
	 * 
	 *  The narrower half of saving: this writes the pipeline as the file the CLI already reads. Saving a
	 *  *project* — the manifest, the style and the pipeline as a directory — is G1 at S5.1, and stays a
	 *  separate command because it has a different scope.
	 */
	saveVpl: (graph: number, path: string) => typedError<DocumentView, VplError>(__TAURI_INVOKE("save_vpl", { graph, path })),
	/**  Everything the OS has asked Studio to open since the last call. */
	takeOpened: () => __TAURI_INVOKE<string[]>("take_opened"),
};

/* Types */
/**
 *  How one source is drawn ([S6.4](../../../docs/scope-release-2.md)).
 * 
 *  **One variant, chosen by what the tiles are.** Before this, a recipe carried a preset, a
 *  recolour, a layer-override map *and* a raster adjustment, and at least half of that was
 *  meaningless for any given source — a preset means nothing over a photograph, and a
 *  `raster-saturation` means nothing over vector tiles. Adding hillshade (S6.6) to a flat struct
 *  would have made it two thirds.
 */
export type Appearance = Appearance_Serialize | Appearance_Deserialize;

/**
 *  How one source is drawn ([S6.4](../../../docs/scope-release-2.md)).
 * 
 *  **One variant, chosen by what the tiles are.** Before this, a recipe carried a preset, a
 *  recolour, a layer-override map *and* a raster adjustment, and at least half of that was
 *  meaningless for any given source — a preset means nothing over a photograph, and a
 *  `raster-saturation` means nothing over vector tiles. Adding hillshade (S6.6) to a flat struct
 *  would have made it two thirds.
 */
export type Appearance_Deserialize = 
/**  Vector tiles: a preset, the adjustments over it, and whatever layers were changed by hand. */
({ type: "vector"; preset: Preset; recolor: Recolor_Deserialize; 
/**  By layer id. Empty for a style nobody has edited by hand. */
overrides: { [key in string]: LayerOverride_Deserialize } }) & { adjust?: never; shade?: never } | 
/**  Raster tiles drawn as an image, adjusted (D11). */
({ type: "raster"; adjust: RasterAdjust_Deserialize }) & { overrides?: never; preset?: never; recolor?: never; shade?: never } | 
/**  Raster tiles holding elevation, drawn as relief (D12). */
({ type: "hillshade"; shade: Hillshade_Deserialize }) & { adjust?: never; overrides?: never; preset?: never; recolor?: never };

/**
 *  How one source is drawn ([S6.4](../../../docs/scope-release-2.md)).
 * 
 *  **One variant, chosen by what the tiles are.** Before this, a recipe carried a preset, a
 *  recolour, a layer-override map *and* a raster adjustment, and at least half of that was
 *  meaningless for any given source — a preset means nothing over a photograph, and a
 *  `raster-saturation` means nothing over vector tiles. Adding hillshade (S6.6) to a flat struct
 *  would have made it two thirds.
 */
export type Appearance_Serialize = 
/**  Vector tiles: a preset, the adjustments over it, and whatever layers were changed by hand. */
({ type: "vector"; preset: Preset; recolor: Recolor_Serialize; 
/**  By layer id. Empty for a style nobody has edited by hand. */
overrides: { [key in string]: LayerOverride_Serialize } }) & { adjust?: never; shade?: never } | 
/**  Raster tiles drawn as an image, adjusted (D11). */
({ type: "raster"; adjust: RasterAdjust_Serialize }) & { overrides?: never; preset?: never; recolor?: never; shade?: never } | 
/**  Raster tiles holding elevation, drawn as relief (D12). */
({ type: "hillshade"; shade: Hillshade_Serialize }) & { adjust?: never; overrides?: never; preset?: never; recolor?: never };

/**
 *  Whether Studio will offer to write this path.
 * 
 *  Checked before the job starts so an unknown extension is a message rather than a job that fails
 *  after opening every source.
 *  What an export narrows the pipeline to before writing it.
 * 
 *  Every field is optional and `None` means "as far as the pipeline goes". They are applied as one
 *  `filter` node appended to the pipeline ([S3.6](../../../docs/scope-release-1.md)) rather than by
 *  clamping numbers we then look at: `filter` is versatiles-rs's own operation for this, so the
 *  source really does stop there and the tile count computed afterwards is the count that will be
 *  written.
 */
export type Bounds = {
	/**  West, south, east, north, in degrees — the four number fields [Q32] asks for. */
	bbox?: [number, number, number, number] | null,
	minZoom?: number | null,
	maxZoom?: number | null,
};

/**
 *  Where the map camera is.
 * 
 *  [Q16](../../docs/decisions.md) is the reason this crosses the boundary at all: a reloaded
 *  webview must come back looking the way the user left it, and the map is the largest thing in
 *  the window to come back wrong.
 */
export type Camera = {
	lng: number,
	lat: number,
	zoom: number,
	/**
	 *  Defaulted, because a [`View`] file written before views had an angle has neither key, and a
	 *  missing angle is a flat north-up view rather than a reason to refuse the whole file.
	 */
	bearing?: number,
	pitch?: number,
};

/**  A file the bundle will carry, and where it will land. */
export type Carried = {
	from: string,
	/**  Its path inside the bundle, `data/berlin.mbtiles`. */
	to: string,
	bytes: number,
};

/**
 *  What Studio knows about a container without reading a single tile body.
 * 
 *  Serialisable so the control plane can hand it to the inspector (A6) verbatim.
 */
export type ContainerInfo = {
	/**  How the user referred to it — a path or a URL. */
	source: string,
	/**  Container kind — just the name: `versatiles`, `mbtiles`, `pmtiles`, `tar`, `directory`. */
	container: string,
	/**  Tile format, e.g. `mvt`, `png`, `webp`. */
	tileFormat: string,
	/**  Tile compression, e.g. `gzip`, `brotli`, `none`. */
	tileCompression: string,
	/**  The zoom levels that actually contain tiles — not what the metadata claims. */
	minZoom: number,
	maxZoom: number,
	/**  `[west, south, east, north]`, if the pyramid is non-empty. */
	bbox: [number, number, number, number] | null,
	/**
	 *  What the container says its tiles *contain*, if it says — `shortbread@1.0`, `dem/mapbox`,
	 *  `rgb`, and the rest of `TileSchema`'s spellings ([S6.1](../../docs/scope-release-2.md)).
	 * 
	 *  **Passed through as the container's own string rather than mirrored into an enum here.**
	 *  `TileSchema` is upstream's and can gain a variant; a copy of its list in Studio would be one
	 *  more thing to keep in step, and the failure mode of falling behind is silently misreading a
	 *  container as something it is not. [`SourceKind`](crate::style::SourceKind) is Studio's
	 *  vocabulary and is derived from this, which is a different question with a different answer.
	 * 
	 *  `None` for every container written before the field existed, which is why nothing may depend
	 *  on it being present.
	 */
	tileSchema: string | null,
	/**
	 *  TileJSON as published by the container, for the inspector to show and edit (A6).
	 * 
	 *  Arbitrary JSON, so it is declared opaque: specta refuses `serde_json::Value` because a
	 *  `Number` can hold an `i64`, and there is no shape to describe beyond "an object".
	 */
	tileJson: any,
};

/**  The control a parameter should be edited with. */
export type Control = { kind: "text" } | 
/**  `min`/`max` come from the integer width, so a zoom level cannot be set to 300. */
{ kind: "number"; integer: boolean; min: number | null; max: number | null } | { kind: "boolean" } | 
/**  An enum, with every accepted spelling. */
{ kind: "choice"; options: string[] } | 
/**  `Vec<String>` — a list of values, written as a VPL array. */
{ kind: "list" } | 
/**  A fixed-size numeric array: a bbox is four, a colour or a centre three. */
{ kind: "numbers"; count: number };

/**  What a copy of this project would carry (S5.1). */
export type CopyPlan = {
	/**  The files that would come along, each once however many pipelines name it. */
	carry: Carried[],
	/**
	 *  References naming a file that is not there — shown, because a copy missing one of these is
	 *  still worth making and the person making it should know.
	 */
	missing: Reference[],
};

/**
 *  How elevation is packed into a DEM's pixels.
 * 
 *  **Two, because those are the two MapLibre can decode.** `versatiles_core` also names
 *  `dem/versatiles`, and nothing published says how to unpack it — a guess would render plausible
 *  hillshade of the wrong mountains, which is worse than saying so. The picker offers these and the
 *  pane says when a container declares something it cannot draw.
 */
export type DemEncoding = "mapbox" | "terrarium";

/**  A problem with a position, ready for the editor to underline. */
export type Diagnostic = {
	message: string,
	span: Span,
};

/**  The whole document a view needs: the text, its tree, and its tokens. */
export type DocumentView = {
	/**
	 *  Which graph this is ([Q32](../../../docs/decisions.md)). The webview addresses everything by
	 *  id rather than by name, so a rename cannot invalidate a reference held mid-edit.
	 */
	graph: number,
	name: string,
	text: string,
	pipeline: Pipeline,
	/**  For the editor to paint, derived from the same tree ([Q25](../../../docs/decisions.md)). */
	tokens: Token[],
	/**  Checked against the operations that exist (C4). A pipeline can parse and still be wrong. */
	diagnostics: Diagnostic[],
	/**  Whether ⌘Z and ⇧⌘Z have anywhere to go, so the interface can say so. */
	canUndo: boolean,
	canRedo: boolean,
	/**  The `.vpl` this came from, if any, so Save has somewhere to write without asking. */
	path: string | null,
	/**  Whether the pipeline differs from what is on disk. */
	dirty: boolean,
};

/**  Where an edit came from. Only the origin matters, not the detail. */
export type EditKind = 
/**  A keystroke in the VPL editor. Consecutive ones merge. */
"typing" | 
/**
 *  A parameter form or the graph — a deliberate, discrete change. The default, because it is
 *  the conservative one: a caller that says nothing gets its own undo step.
 */
"structured" | 
/**  The document was replaced wholesale, e.g. by opening a file. */
"replaced";

/**
 *  What is running this, for the header of a copied report.
 * 
 *  **Half of it can only be answered here.** The webview knows its own engine and its GPU; the
 *  build number, the platform and where home is are the process's to say. `home` is not shown
 *  anywhere — it is what the report redacts out of file paths before anybody pastes them into a
 *  public issue.
 */
export type Environment = {
	appVersion: string,
	/**  `macos`, `windows`, `linux` — `std::env::consts`, so it is the target this was built for. */
	os: string,
	arch: string,
	/**  The system webview's version, or `None` where it will not say. */
	webview: string | null,
	/**  The user's home directory, for redaction. `None` when the platform has no answer. */
	home: string | null,
	/**
	 *  The file this session is being written to, for the panel to name.
	 * 
	 *  **Worth naming rather than hiding.** Someone whose window will not open at all cannot reach
	 *  the panel, and a path they can be told over a chat is the difference between a report and a
	 *  shrug.
	 */
	log: string,
};

/**  What an export is expected to cost. */
export type Estimate = {
	/**  Tiles the export will write — a count, not an estimate. */
	tiles: number,
	/**  Bytes those tiles are expected to come to. */
	bytes: number,
	/**  Seconds the write is expected to take. */
	seconds: number,
	/**
	 *  How many tiles were actually produced to arrive at the two numbers above.
	 * 
	 *  Reported because it is the honest measure of how much the estimate is worth, and the only
	 *  one the webview could not work out for itself. Four samples of a slow pipeline and sixty of
	 *  a fast one deserve different wording.
	 */
	sampled: number,
};

/**  A family someone can install, and whether they have. */
export type Family = {
	/**  The name the archive and the font stack share — `noto_sans`. */
	id: string,
	/**  Download size, so a 48 MB decision is made before it starts rather than during. */
	bytes: number,
	installed: boolean,
};

/**  One parameter of an operation, ready to render. */
export type FieldInfo = {
	name: string,
	/**  Upstream's own documentation for the parameter. */
	doc: string,
	required: boolean,
	/**  Fed by a `[ … ]` block rather than by a `key=value` pair, so it has no control. */
	sources: boolean,
	control: Control,
	/**
	 *  What the operation does when this parameter is absent, spelled as VPL would write it
	 *  ([vt#253]). `None` when there is no literal to show.
	 * 
	 *  **Shown, never filled in.** An empty box for `from_color`'s `color` and an empty box for
	 *  `from_csv`'s `lon_column` used to look identical, and one of them means `000000` while the
	 *  other means the pipeline will not build. Writing the default into the document instead would
	 *  turn every form into a wall of restated defaults and freeze today's value into a file that
	 *  should follow whatever the operation does next.
	 * 
	 *  `None` is not "required": an optional parameter with no default is one whose absence *does*
	 *  something — `filter`'s `bbox` clips nothing at all when unset — and a form has nothing to
	 *  say about those.
	 * 
	 *  [vt#253]: https://github.com/versatiles-org/versatiles-rs/issues/253
	 */
	default: string | null,
};

/**  What one field could be set to. */
export type FieldSuggestion = {
	field: string,
	values: string[],
};

/**  Whether one transform can be appended to what a node produces (S2.14). */
export type Fit = {
	/**  The operation's tag, as it would be written in VPL. */
	name: string,
	/**
	 *  Why it does not fit, in upstream's words — or `None` when nothing rules it out.
	 * 
	 *  The reason is the whole point of reporting the misfits at all: a picker that silently
	 *  dropped `raster_flatten` from a vector chain would leave someone looking for an operation
	 *  they know exists.
	 */
	reason: string | null,
};

/**  One graph: a VPL document, what it is called, and where it came from. */
export type GraphInfo = {
	id: number,
	name: string,
	/**  The `.vpl` this came from, if any, so Save has somewhere to write without asking. */
	path: string | null,
	/**  Whether the document differs from what is on disk. */
	dirty: boolean,
	/**  What an export of this graph is narrowed to (F2, S5.2) — empty until someone sets one. */
	crop: Bounds,
};

/**
 *  How elevation is drawn as relief ([S6.6](../../../docs/scope-release-2.md), D12).
 * 
 *  **`None` is "leave it alone"**, as everywhere else here: an untouched setting serialises to
 *  nothing, so a fresh recipe and an untouched one compare equal and the undo stack stays quiet.
 */
export type Hillshade = Hillshade_Serialize | Hillshade_Deserialize;

/**
 *  How elevation is drawn as relief ([S6.6](../../../docs/scope-release-2.md), D12).
 * 
 *  **`None` is "leave it alone"**, as everywhere else here: an untouched setting serialises to
 *  nothing, so a fresh recipe and an untouched one compare equal and the undo stack stays quiet.
 */
export type Hillshade_Deserialize = {
	/**  `None` takes the container's declared schema, which is right whenever there is one. */
	encoding?: DemEncoding | null,
	/**  `0` to `1`, how hard the relief is pushed. */
	exaggeration?: number | null,
	/**  Where the light comes from, in degrees. */
	direction?: number | null,
	/**  How high the light sits, `0` (horizon) to `90` (overhead). */
	altitude?: number | null,
	/**  Hex colours, as MapLibre takes them. */
	shadow?: string | null,
	highlight?: string | null,
	accent?: string | null,
};

/**
 *  How elevation is drawn as relief ([S6.6](../../../docs/scope-release-2.md), D12).
 * 
 *  **`None` is "leave it alone"**, as everywhere else here: an untouched setting serialises to
 *  nothing, so a fresh recipe and an untouched one compare equal and the undo stack stays quiet.
 */
export type Hillshade_Serialize = {
	/**  `None` takes the container's declared schema, which is right whenever there is one. */
	encoding?: DemEncoding | null,
	/**  `0` to `1`, how hard the relief is pushed. */
	exaggeration?: number | null,
	/**  Where the light comes from, in degrees. */
	direction?: number | null,
	/**  How high the light sits, `0` (horizon) to `90` (overhead). */
	altitude?: number | null,
	/**  Hex colours, as MapLibre takes them. */
	shadow?: string | null,
	highlight?: string | null,
	accent?: string | null,
};

/**  One way of bringing data in. */
export type ImportKind = {
	/**  Stable identifier, used by the caller to say which card was chosen. */
	id: string,
	/**  What the card says. */
	label: string,
	/**  The one-line explanation under it. */
	detail: string,
	/**  Extensions for the file dialog and the drop filter, without the dot, lowercase. */
	extensions: string[],
	/**
	 *  The read operation a chosen file becomes.
	 * 
	 *  `None` for a `.vpl`, which is not a node — it is a whole document, and opening one replaces
	 *  the pipeline rather than adding to it (C9).
	 */
	operation: string | null,
	/**
	 *  Required parameters a filename cannot supply, in the order the operation declares them.
	 * 
	 *  Empty means picking a file completes the import. Anything here has to come from somewhere
	 *  else: the file's own header, or the person.
	 */
	needs: string[],
};

/**
 *  A job as the status bar lists it.
 * 
 *  The log is deliberately **not** here: listing jobs happens on every reload, and shipping a
 *  thousand lines per job to draw one progress bar is a cost paid for something nobody is looking
 *  at. [`Jobs::log`] fetches it when a row is expanded.
 */
export type Job = {
	id: number,
	/**  What to call it in the bar — "Building preview", "Converting berlin.mbtiles". */
	label: string,
	lane: Lane,
	state: JobState,
	/**  `0.0..=1.0`, or `None` when the job cannot say — which is honest more often than not. */
	fraction: number | null,
	/**
	 *  How many units are done and how many there are, when the job counts in units at all.
	 * 
	 *  A fraction alone cannot say how *fast* anything is going: "43% per minute" is not a speed
	 *  anybody recognises. These are what make "12,400 tiles/s" possible, and the runtime already
	 *  reports them — they used to be divided into a fraction and thrown away.
	 */
	done: number | null,
	total: number | null,
	/**
	 *  Units per second, averaged since the first counted update.
	 * 
	 *  Averaged rather than instantaneous, because an ETA that jumps between "2 minutes" and "40
	 *  minutes" every second is worse than no ETA. Anchored at the first update rather than at
	 *  submission, so the time spent opening sources before any tile moved is not counted as slow
	 *  tiles.
	 */
	rate: number | null,
	/**  Seconds remaining at that rate, or `None` until there is enough to say. */
	etaSeconds: number | null,
	/**  What is happening right now. Empty until the job says something. */
	message: string,
	/**
	 *  How many lines the log holds, so a row can offer to expand only when there is something in
	 *  it.
	 */
	logLines: number,
};

/**
 *  Everything a running job can tell the outside world.
 * 
 *  `Serialize` so the boundary can forward it verbatim; nothing here is Tauri-specific.
 * 
 *  The webview builds its list from these rather than polling: a progress bar driven by a `list()`
 *  call every 200ms is both slower to update and more work than being told.
 */
export type JobEvent = 
/**
 *  A job exists. Carries the whole record, so a listener never has to ask what it just heard
 *  about.
 */
{ kind: "added"; job: Job } | 
/**  It left the queue and started running. */
{ kind: "started"; id: number } | 
/**  Fractional progress in `0.0..=1.0` — or `None`, plus what is happening right now. */
{ kind: "progress"; id: number; fraction: number | null; 
/**
 *  Absolute counts when the job has them. The runner turns successive values into a rate
 *  and an ETA; a listener never has to keep its own history to know how fast this is going.
 */
done: number | null; total: number | null; message: string } | 
/**  A line for the job log. Failures at minute forty have to be able to say why. */
{ kind: "log"; id: number; line: string; 
/**
 *  How many lines the log holds *after* this one — filled in by the runner on the way out.
 * 
 *  Carried rather than counted by the listener, because the log is capped: a mirror that
 *  incremented its own counter would keep climbing past [`LOG_LINES`] and claim a size the
 *  log does not have.
 */
logLines: number } | 
/**  The job finished on its own. */
{ kind: "finished"; id: number } | 
/**  The job stopped because it was cancelled. */
{ kind: "cancelled"; id: number } | 
/**  The job stopped because it failed. */
{ kind: "failed"; id: number; error: string };

/**  Where a job is in its life. */
export type JobState = 
/**  Submitted, waiting for the lane to free up. Only [`Lane::Queued`] jobs are ever here. */
{ kind: "queued" } | { kind: "running" } | { kind: "finished" } | { kind: "cancelled" } | { kind: "failed"; error: string };

/**  How a job relates to the ones already in flight. */
export type Lane = 
/**
 *  One at a time, in submission order.
 * 
 *  Conversions compete for the same disk and the same cores; two at once finish later than the
 *  same two in sequence, and report progress that means nothing while they do it.
 */
"queued" | 
/**
 *  Newest wins — submitting cancels whatever this lane was already running.
 * 
 *  For work whose answer stops mattering the moment it is asked again: a preview of a pipeline
 *  that has since been edited is not a result anybody will look at, it is a machine still
 *  warming up over a stale question.
 */
"latest";

/**  One layer of a decoded vector tile (A4). */
export type LayerInspection = {
	name: string,
	featureCount: number,
	/**  Exact encoded size of this layer, so "which layer is eating my tile" has an answer. */
	encodedBytes: number,
	/**  Property keys present, for a first look at what is styleable. */
	propertyKeys: string[],
	/**
	 *  What this layer is made of: `point`, `line`, `polygon`, or `unknown` (S4.4, D2).
	 * 
	 *  **The commonest of its features, not all of them.** A layer may mix geometries and MapLibre
	 *  draws one kind per layer, so a style deriving itself from this has to pick — and the majority
	 *  is the pick that leaves the fewest features invisible. Free to compute: the type is a field on
	 *  every feature, already read by the time the tile has decoded.
	 */
	geometry: string,
};

/**
 *  What was changed about one layer by hand (D3).
 * 
 *  **Sparse, and only these three.** [D3](../../../docs/features.md) asks for filter, zoom range and
 *  paint, all of which are properties *of* a layer — none of them adds, removes or reorders one,
 *  which is what keeps a patch enough and a whole style unnecessary. [Q36] records that limit as
 *  accepted rather than overlooked.
 * 
 *  `paint` and `filter` are opaque JSON, declared so for the same reason as
 *  `ContainerInfo::tile_json`: specta refuses `serde_json::Value` because a `Number` can hold an
 *  `i64`, and there is no shape to describe here beyond "whatever MapLibre accepts". A type for
 *  them would be a second, worse copy of the style specification that has to be kept in step.
 */
export type LayerOverride = LayerOverride_Serialize | LayerOverride_Deserialize;

/**
 *  What was changed about one layer by hand (D3).
 * 
 *  **Sparse, and only these three.** [D3](../../../docs/features.md) asks for filter, zoom range and
 *  paint, all of which are properties *of* a layer — none of them adds, removes or reorders one,
 *  which is what keeps a patch enough and a whole style unnecessary. [Q36] records that limit as
 *  accepted rather than overlooked.
 * 
 *  `paint` and `filter` are opaque JSON, declared so for the same reason as
 *  `ContainerInfo::tile_json`: specta refuses `serde_json::Value` because a `Number` can hold an
 *  `i64`, and there is no shape to describe here beyond "whatever MapLibre accepts". A type for
 *  them would be a second, worse copy of the style specification that has to be kept in step.
 */
export type LayerOverride_Deserialize = {
	/**  Painted or not. `None` leaves the preset's own answer alone. */
	visible?: boolean | null,
	minZoom?: number | null,
	maxZoom?: number | null,
	/**  Paint properties to merge over the layer's own, by MapLibre's names. */
	paint?: any | null,
	/**  A MapLibre filter expression, replacing the layer's own. */
	filter?: any | null,
};

/**
 *  What was changed about one layer by hand (D3).
 * 
 *  **Sparse, and only these three.** [D3](../../../docs/features.md) asks for filter, zoom range and
 *  paint, all of which are properties *of* a layer — none of them adds, removes or reorders one,
 *  which is what keeps a patch enough and a whole style unnecessary. [Q36] records that limit as
 *  accepted rather than overlooked.
 * 
 *  `paint` and `filter` are opaque JSON, declared so for the same reason as
 *  `ContainerInfo::tile_json`: specta refuses `serde_json::Value` because a `Number` can hold an
 *  `i64`, and there is no shape to describe here beyond "whatever MapLibre accepts". A type for
 *  them would be a second, worse copy of the style specification that has to be kept in step.
 */
export type LayerOverride_Serialize = {
	/**  Painted or not. `None` leaves the preset's own answer alone. */
	visible?: boolean | null,
	minZoom?: number | null,
	maxZoom?: number | null,
	/**  Paint properties to merge over the layer's own, by MapLibre's names. */
	paint?: any | null,
	/**  A MapLibre filter expression, replacing the layer's own. */
	filter?: any | null,
};

/**
 *  Which left-pane sections are open, and how wide the pane is ([Q22]).
 * 
 *  This lives in the core rather than the webview for the reason everything else here does ([Q16]):
 *  a reloaded window must come back looking the way the user left it. Q22 called independent,
 *  remembered collapse "load-bearing, not polish" — on the 13-inch laptop Q15 was protecting, a
 *  pane that reopens everything on every reload makes the surface unusable.
 * 
 *  **A list of panes, not named fields** ([Q31]). Which panes exist is still a design decision
 *  rather than something the webview can invent — the catalogue below is code — but their *order*
 *  and *which sidebar they sit in* are data, so moving one is an edit rather than a refactor. The
 *  analysis cluster alone adds eight more of them.
 * 
 *  **`default` is for the file, and it shows in the generated bindings.** It exists so a
 *  `layout.json` written by an earlier build still loads; the generator cannot know that, so every
 *  field arrives in TypeScript as optional even though a command always returns all of them. One
 *  struct serving as both a file format and an IPC type is what makes that ambiguous.
 */
export type Layout = {
	/**
	 *  Every pane, in the order its sidebar shows it. Reconciled against the catalogue on the way
	 *  in, so a file from another build is never authoritative about which panes exist.
	 */
	panes?: PaneState[],
	/**  Pane widths in CSS pixels. Both edges are draggable. */
	leftWidth?: number,
	rightWidth?: number,
	/**
	 *  Which background map the map sits on, or `none`.
	 * 
	 *  Held as a plain string rather than an enum: the catalogue is a webview concern, and the core
	 *  has no reason to know what `graybeard` is. The webview rejects a value it does not recognise,
	 *  so an old file cannot break the map.
	 */
	background?: string,
	/**
	 *  Where the camera was, or `None` if it has never been moved.
	 * 
	 *  Here rather than in a file of its own because it is window state with exactly this recovery
	 *  policy — a camera that will not parse costs nothing to forget — and because `background`,
	 *  also a map setting rather than a pane one, already lives here.
	 * 
	 *  `None` is not the same as a default camera: it means *nothing to restore*, so a first run
	 *  still fits the view to whatever is opened instead of jumping to null island.
	 */
	view?: Camera | null,
};

/**
 *  How much attention an entry deserves.
 * 
 *  Two levels, not five. This is a list of *problems* — anything worth a level below "something did
 *  not work" belongs in a job's log or in nothing at all, and a level nobody filters on is a column
 *  nobody reads.
 */
export type Level = 
/**  Something was given up on, and the application carried on without it. */
"warn" | 
/**  Something the user asked for did not happen. */
"error";

/**  A problem on its way in, before the ring gives it an id, a time and a count. */
export type NewProblem = {
	level: Level,
	origin: Origin,
	message: string,
	detail: string | null,
};

/**  One operation, its parameters, and any nested pipelines feeding it. */
export type Node = {
	name: string,
	nameSpan: Span,
	/**
	 *  **In source order, with duplicates kept.** The semantic tree stores a `BTreeMap`, which sorts
	 *  the keys and merges repeats; rewriting a file through that would reorder parameters the
	 *  author deliberately arranged.
	 */
	properties: Property[],
	/**  Nested pipelines from the `[…]` block, if there is one. */
	sources: Pipeline[],
	/**  The `[…]` block itself, brackets included. */
	sourcesSpan: Span | null,
	/**  Name through the end of the sources block. */
	span: Span,
};

/**  What one node's fields could take. */
export type NodeSuggestions = {
	/**  The node's path, as `0.1.2`. */
	path: string,
	fields: FieldSuggestion[],
};

export type OpenedContainer = {
	/**  Mount name on the embedded server. */
	name: string,
	/**  Ready-made template for MapLibre; the port is ephemeral, so it is never assumed. */
	tileUrl: string,
	/**  The `from_container` node this container corresponds to in the pipeline (Q22). */
	vpl: string,
	info: ContainerInfo,
};

/**  One operation, ready to render. */
export type OperationInfo = {
	name: string,
	/**  `read` or `transform` — which end of a pipeline it belongs at. */
	kind: string,
	/**  What it does, in a sentence. */
	summary: string,
	/**
	 *  Everything else upstream has to say, minus the parameter list — that is `fields`, and
	 *  sending it twice is what [vt#229] was about. Empty when the summary is the whole of it.
	 * 
	 *  [vt#229]: https://github.com/versatiles-org/versatiles-rs/issues/229
	 */
	details: string,
	fields: FieldInfo[],
};

/**
 *  Which half of the application an entry came from.
 * 
 *  Worth keeping apart because it decides who reads it: `Core` is Rust, `Webview` is the window,
 *  and `Map` is MapLibre reporting about tiles and styles — the one that is nobody's code and
 *  therefore the easiest to misattribute.
 */
export type Origin = "core" | "webview" | "map";

/**
 *  One pane's place in the layout.
 * 
 *  The id is the whole contract with the webview: the core decides where a pane sits and whether it
 *  is open, the webview decides what it contains and what it is called. A title is presentation, so
 *  it is not stored — it would be one more thing to keep in step across a boundary for no gain.
 */
export type PaneState = {
	id: string,
	side: Side,
	open: boolean,
};

/**  Which node the map shows, overriding every mounted graph. */
export type Pin = {
	graph: number,
	path: number[],
};

/**  A chain of nodes, `a | b | c`. */
export type Pipeline = {
	nodes: Node[],
	span: Span,
};

/**
 *  Where a style starts before anything is adjusted.
 * 
 *  The six are `@versatiles/style`'s own builders, named as it names them so the webview needs no
 *  translation table — a mapping between two spellings of the same six things is a thing to keep in
 *  step for no gain.
 */
export type Preset = "colorful" | "eclipse" | "graybeard" | "neutrino" | "shadow" | "satellite" | 
/**
 *  Built from the layers the tiles actually contain, rather than from a Shortbread assumption
 *  (D2, S4.4). A recipe rather than a fixed style, so it re-derives when the pipeline changes.
 */
"derived";

/**  The pipeline's output, mounted on the embedded server and ready for the map (S2.7, C3). */
export type Preview = {
	/**  Mount name, stable so a rebuild replaces rather than accumulates. */
	name: string,
	tileUrl: string,
	info: ContainerInfo,
	/**
	 *  The layers this produces, with their property keys (S3.3, E1).
	 * 
	 *  Carried on the preview rather than fetched separately because it is an answer about *this*
	 *  build: asking afterwards would race the next edit, and the form would offer property names
	 *  from a pipeline that no longer exists. Empty for raster output.
	 */
	layers: LayerInspection[],
	/**
	 *  Which transforms can be appended to this, and why the rest cannot (S2.14).
	 * 
	 *  Carried here for the same reason as `layers`, and it is the same kind of answer: what fits
	 *  depends on what this build produces, so asking separately would race the next edit and offer
	 *  operations chosen for a pipeline that no longer exists. It also costs nothing extra — the
	 *  source is already built and every check is a comparison against its declared tile type.
	 */
	fits: Fit[],
};

/**
 *  What a preview request came to.
 * 
 *  Three outcomes rather than an `Option`, because "there is nothing at that path" and "you asked
 *  again before I finished" are different facts and the caller does different things with them.
 */
export type PreviewOutcome = {
	kind: "ready",
} & Preview | 
/**  The path names no node, or there is no pipeline yet. */
{ kind: "nothing" } | 
/**  A newer preview replaced this one before it finished. Its answer is the current one. */
{ kind: "superseded" };

/**  One problem, as the panel lists it and the report prints it. */
export type Problem = {
	id: number,
	/**
	 *  Whole seconds since the Unix epoch.
	 * 
	 *  A wall clock rather than an elapsed time, because the number that matters in an issue is
	 *  "before or after the thing I was doing". Seconds rather than milliseconds because specta
	 *  renders an `f64` as `number | null` — JSON cannot promise it a NaN — and a time that has to
	 *  be null-checked at every use is a worse trade than a second of precision nobody reads. Ties
	 *  are broken by `id`, which is monotonic.
	 */
	at: number,
	level: Level,
	origin: Origin,
	/**  One line, and the thing repeats are matched on. */
	message: string,
	/**  The rest of it — a stack, an error chain, a panic's location. Often the whole answer. */
	detail: string | null,
	/**  How many times this happened. `1` for a problem that happened once. */
	count: number,
};

/**  One `key=value` pair. */
export type Property = {
	key: string,
	keySpan: Span,
	value: Value,
	/**  `key` through the end of the value. */
	span: Span,
};

/**  How a string was written. Mirrors upstream's `CstStringKind`. */
export type Quote = 
/**  Bare, e.g. `mvt` or `13.4`. */
"none" | 
/**  `'…'` — no escape processing. */
"single" | 
/**  `"…"` — `\\`, `\"`, `\n` and `\t` are unescaped. */
"double";

/**
 *  How imagery is adjusted when a source is drawn as raster ([S6.3](../../../docs/scope-release-2.md), D11).
 * 
 *  **Its own type rather than a second reading of [`Recolor`].** The two describe the same five
 *  ideas and only two of them share a parameterisation: `rotate` and `saturate` mean what
 *  `raster-hue-rotate` and `raster-saturation` mean, while `Recolor`'s contrast is a multiplier
 *  around 1 and MapLibre's is an offset around 0, and `Recolor`'s brightness is an offset where
 *  MapLibre's is a pair of range endpoints. Reusing the struct would have meant a conversion nobody
 *  could read and two controls whose numbers lied about what they did.
 * 
 *  **`None` is "leave it alone", not a neutral value.** The same reason `Recolor` gives: an
 *  untouched adjustment must serialise to nothing, or every project file would carry a list of
 *  identity values and every recipe would compare unequal to a fresh one.
 */
export type RasterAdjust = RasterAdjust_Serialize | RasterAdjust_Deserialize;

/**
 *  How imagery is adjusted when a source is drawn as raster ([S6.3](../../../docs/scope-release-2.md), D11).
 * 
 *  **Its own type rather than a second reading of [`Recolor`].** The two describe the same five
 *  ideas and only two of them share a parameterisation: `rotate` and `saturate` mean what
 *  `raster-hue-rotate` and `raster-saturation` mean, while `Recolor`'s contrast is a multiplier
 *  around 1 and MapLibre's is an offset around 0, and `Recolor`'s brightness is an offset where
 *  MapLibre's is a pair of range endpoints. Reusing the struct would have meant a conversion nobody
 *  could read and two controls whose numbers lied about what they did.
 * 
 *  **`None` is "leave it alone", not a neutral value.** The same reason `Recolor` gives: an
 *  untouched adjustment must serialise to nothing, or every project file would carry a list of
 *  identity values and every recipe would compare unequal to a fresh one.
 */
export type RasterAdjust_Deserialize = {
	/**  Degrees, `-180` to `180`. */
	hue?: number | null,
	/**  `-1` to `1`, where `0` leaves it alone. */
	saturation?: number | null,
	/**  `-1` to `1`, where `0` leaves it alone. */
	contrast?: number | null,
	/**
	 *  `-1` to `1`, where `0` leaves it alone.
	 * 
	 *  Studio's own control, converted to `raster-brightness-min`/`-max` when the style is built:
	 *  MapLibre remaps the input range onto those two endpoints, which is two numbers for something
	 *  people reach for as one.
	 */
	brightness?: number | null,
	/**  `0` to `1`. */
	opacity?: number | null,
	/**
	 *  `linear` smooths between pixels, `nearest` keeps them square — which is what a scan of a
	 *  printed map or any pixel art wants.
	 */
	resampling?: Resampling | null,
};

/**
 *  How imagery is adjusted when a source is drawn as raster ([S6.3](../../../docs/scope-release-2.md), D11).
 * 
 *  **Its own type rather than a second reading of [`Recolor`].** The two describe the same five
 *  ideas and only two of them share a parameterisation: `rotate` and `saturate` mean what
 *  `raster-hue-rotate` and `raster-saturation` mean, while `Recolor`'s contrast is a multiplier
 *  around 1 and MapLibre's is an offset around 0, and `Recolor`'s brightness is an offset where
 *  MapLibre's is a pair of range endpoints. Reusing the struct would have meant a conversion nobody
 *  could read and two controls whose numbers lied about what they did.
 * 
 *  **`None` is "leave it alone", not a neutral value.** The same reason `Recolor` gives: an
 *  untouched adjustment must serialise to nothing, or every project file would carry a list of
 *  identity values and every recipe would compare unequal to a fresh one.
 */
export type RasterAdjust_Serialize = {
	/**  Degrees, `-180` to `180`. */
	hue?: number | null,
	/**  `-1` to `1`, where `0` leaves it alone. */
	saturation?: number | null,
	/**  `-1` to `1`, where `0` leaves it alone. */
	contrast?: number | null,
	/**
	 *  `-1` to `1`, where `0` leaves it alone.
	 * 
	 *  Studio's own control, converted to `raster-brightness-min`/`-max` when the style is built:
	 *  MapLibre remaps the input range onto those two endpoints, which is two numbers for something
	 *  people reach for as one.
	 */
	brightness?: number | null,
	/**  `0` to `1`. */
	opacity?: number | null,
	/**
	 *  `linear` smooths between pixels, `nearest` keeps them square — which is what a scan of a
	 *  printed map or any pixel art wants.
	 */
	resampling?: Resampling | null,
};

export type RecentEntry = {
	/**  The path or URL exactly as the user gave it. */
	source: string,
	/**
	 *  Seconds since the Unix epoch, emitted as a `number` — a double holds them exactly for the
	 *  next quarter of a million years, and `u32` would overflow in 2106.
	 */
	openedAt: number,
};

/**
 *  The whole style, as the core holds it.
 * 
 *  **One entry per source, keyed by the graph's name.** The name is what a MapLibre style calls a
 *  source and what `project.yaml` already lists graphs by, so persisting under it means the manifest
 *  and the style agree without a translation table. It is *not* how the running application refers
 *  to a graph — that is [`GraphId`](crate::graphs::GraphId), for the reason `graphs.rs` gives — so a
 *  rename has to move the entry, which is [`Recipe::rename_source`]'s whole job.
 * 
 *  Ordered (`BTreeMap`, not `HashMap`) so the text this serialises to depends only on its contents.
 *  The undo stack compares snapshots to decide whether anything changed, and a map that iterated
 *  differently between two identical states would record an edit every time the style was touched.
 */
export type Recipe = Recipe_Serialize | Recipe_Deserialize;

/**
 *  The whole style, as the core holds it.
 * 
 *  **One entry per source, keyed by the graph's name.** The name is what a MapLibre style calls a
 *  source and what `project.yaml` already lists graphs by, so persisting under it means the manifest
 *  and the style agree without a translation table. It is *not* how the running application refers
 *  to a graph — that is [`GraphId`](crate::graphs::GraphId), for the reason `graphs.rs` gives — so a
 *  rename has to move the entry, which is [`Recipe::rename_source`]'s whole job.
 * 
 *  Ordered (`BTreeMap`, not `HashMap`) so the text this serialises to depends only on its contents.
 *  The undo stack compares snapshots to decide whether anything changed, and a map that iterated
 *  differently between two identical states would record an edit every time the style was touched.
 */
export type Recipe_Deserialize = {
	/**  By graph name. */
	sources?: { [key in string]: SourceStyle_Deserialize },
	/**
	 *  Draw order, bottom first ([S6.5](../../../docs/scope-release-2.md)).
	 * 
	 *  **A list beside the map rather than a number on each entry.** Reordering is a drag, and a
	 *  drag that has to renumber every sibling is how two entries end up claiming one position.
	 *  Names absent from it are drawn after those in it, in name order — so a source that arrives
	 *  while nobody is looking appears on top rather than vanishing.
	 */
	order?: string[],
};

/**
 *  The whole style, as the core holds it.
 * 
 *  **One entry per source, keyed by the graph's name.** The name is what a MapLibre style calls a
 *  source and what `project.yaml` already lists graphs by, so persisting under it means the manifest
 *  and the style agree without a translation table. It is *not* how the running application refers
 *  to a graph — that is [`GraphId`](crate::graphs::GraphId), for the reason `graphs.rs` gives — so a
 *  rename has to move the entry, which is [`Recipe::rename_source`]'s whole job.
 * 
 *  Ordered (`BTreeMap`, not `HashMap`) so the text this serialises to depends only on its contents.
 *  The undo stack compares snapshots to decide whether anything changed, and a map that iterated
 *  differently between two identical states would record an edit every time the style was touched.
 */
export type Recipe_Serialize = {
	/**  By graph name. */
	sources: { [key in string]: SourceStyle_Serialize },
	/**
	 *  Draw order, bottom first ([S6.5](../../../docs/scope-release-2.md)).
	 * 
	 *  **A list beside the map rather than a number on each entry.** Reordering is a drag, and a
	 *  drag that has to renumber every sibling is how two entries end up claiming one position.
	 *  Names absent from it are drawn after those in it, in name order — so a source that arrives
	 *  while nobody is looking appears on top rather than vanishing.
	 */
	order: string[],
};

/**
 *  The adjustments applied to every colour in the style at once (D1).
 * 
 *  A mirror of `@versatiles/style`'s `RecolorOptions`, field for field. Mirrored rather than
 *  wrapped: these cross the IPC boundary and are handed to the generator unchanged, so a field this
 *  end that the generator does not have would be a setting that silently does nothing.
 * 
 *  Every field is optional and `None` means "leave it alone". `skip_serializing_if` on each is what
 *  makes that true in the text as well as in the type: without it an untouched recolour serialises
 *  as ten `null`s, which is both larger than the recipe it belongs to and a lie about having been
 *  configured.
 */
export type Recolor = Recolor_Serialize | Recolor_Deserialize;

/**
 *  The adjustments applied to every colour in the style at once (D1).
 * 
 *  A mirror of `@versatiles/style`'s `RecolorOptions`, field for field. Mirrored rather than
 *  wrapped: these cross the IPC boundary and are handed to the generator unchanged, so a field this
 *  end that the generator does not have would be a setting that silently does nothing.
 * 
 *  Every field is optional and `None` means "leave it alone". `skip_serializing_if` on each is what
 *  makes that true in the text as well as in the type: without it an untouched recolour serialises
 *  as ten `null`s, which is both larger than the recipe it belongs to and a lie about having been
 *  configured.
 */
export type Recolor_Deserialize = {
	/**  Swap light for dark while keeping the hues — D5's whole feature, in one flag. */
	invertBrightness?: boolean | null,
	/**  Hue rotation, in degrees. */
	rotate?: number | null,
	saturate?: number | null,
	gamma?: number | null,
	contrast?: number | null,
	brightness?: number | null,
	tint?: number | null,
	tintColor?: string | null,
	blend?: number | null,
	blendColor?: string | null,
};

/**
 *  The adjustments applied to every colour in the style at once (D1).
 * 
 *  A mirror of `@versatiles/style`'s `RecolorOptions`, field for field. Mirrored rather than
 *  wrapped: these cross the IPC boundary and are handed to the generator unchanged, so a field this
 *  end that the generator does not have would be a setting that silently does nothing.
 * 
 *  Every field is optional and `None` means "leave it alone". `skip_serializing_if` on each is what
 *  makes that true in the text as well as in the type: without it an untouched recolour serialises
 *  as ten `null`s, which is both larger than the recipe it belongs to and a lie about having been
 *  configured.
 */
export type Recolor_Serialize = {
	/**  Swap light for dark while keeping the hues — D5's whole feature, in one flag. */
	invertBrightness?: boolean | null,
	/**  Hue rotation, in degrees. */
	rotate?: number | null,
	saturate?: number | null,
	gamma?: number | null,
	contrast?: number | null,
	brightness?: number | null,
	tint?: number | null,
	tintColor?: string | null,
	blend?: number | null,
	blendColor?: string | null,
};

/**  One file a pipeline names. */
export type Reference = {
	/**  The graph it was found in. */
	graph: string,
	/**  The parameter, as written — `filename`, `data_source_path`, … */
	field: string,
	/**  What it says, before any rewriting. */
	value: string,
	kind: ReferenceKind,
};

/**  What one reference turned out to be. */
export type ReferenceKind = 
/**  A URL. Works from anywhere, so it is neither carried nor rewritten. */
{ kind: "remote" } | 
/**  A file that is there. */
{ kind: "local"; path: string; 
/**  Its size, so a surface can say what a bundle will cost before writing it. */
bytes: number } | 
/**
 *  Named, and not where it says. Carried as nothing; the pipeline keeps the name it had, so a
 *  bundle opened somewhere the file *does* exist still works.
 */
{ kind: "missing"; path: string };

/**  How a raster is sampled when it is scaled. */
export type Resampling = "linear" | "nearest";

/**
 *  What a step back or forward restored.
 * 
 *  **The step says which document it changed**, because one stack now spans the graphs and the
 *  style ([Q36]) and the webview has to know which of them to redraw. Returning only a graph view
 *  would have made undoing a style edit look like nothing happened.
 * 
 *  [Q36]: ../../../docs/decisions.md
 */
export type Restored = Restored_Serialize | Restored_Deserialize;

/**
 *  What a step back or forward restored.
 * 
 *  **The step says which document it changed**, because one stack now spans the graphs and the
 *  style ([Q36]) and the webview has to know which of them to redraw. Returning only a graph view
 *  would have made undoing a style edit look like nothing happened.
 * 
 *  [Q36]: ../../../docs/decisions.md
 */
export type Restored_Deserialize = ({ graph: DocumentView }) & { style?: never } | ({ style: Recipe_Deserialize }) & { graph?: never };

/**
 *  What a step back or forward restored.
 * 
 *  **The step says which document it changed**, because one stack now spans the graphs and the
 *  style ([Q36]) and the webview has to know which of them to redraw. Returning only a graph view
 *  would have made undoing a style edit look like nothing happened.
 * 
 *  [Q36]: ../../../docs/decisions.md
 */
export type Restored_Serialize = ({ graph: DocumentView }) & { style?: never } | ({ style: Recipe_Serialize }) & { graph?: never };

/**
 *  What the editor needs on every keystroke: how to paint the text, and what is wrong with it.
 * 
 *  One command rather than two, because they are answers to the same parse — asking separately
 *  would parse the same text twice and let the highlighting and the diagnostics disagree about
 *  which version they describe.
 */
export type Review = {
	tokens: Token[],
	/**
	 *  Empty when the pipeline is sound. Parse failures come back as an `Err` instead — a document
	 *  that does not parse has no tree to validate.
	 */
	diagnostics: Diagnostic[],
};

/**  Which sidebar a pane sits in. */
export type Side = "left" | "right";

/**
 *  What a source's tiles are, as far as drawing them is concerned ([S6.1](../../../docs/scope-release-2.md)).
 * 
 *  **Studio's vocabulary, not the container's.** A container declares a `tile_schema` — upstream's
 *  list, which can grow — and this is the much smaller question the style pane actually switches on:
 *  which editor does this source get. Two schemas can land on one kind (`rgb` and `rgba` are both
 *  imagery) and a container with no schema at all still has to land somewhere.
 * 
 *  **Derived, and overridable.** The webview works it out from the schema, falling back to the tile
 *  format and the layers the probe found. That answer is a guess whenever the schema is absent, so
 *  [`Recipe::kind`] exists to let someone correct it — a DEM written before `tile_schema` existed is
 *  otherwise indistinguishable from a photograph, and no amount of looking at the pixels decides it.
 */
export type SourceKind = 
/**  Vector tiles using Shortbread's layer names, which the six presets are written against. */
"vectorShortbread" | 
/**  Vector tiles of anything else. Styled from the layers actually present (D2). */
"vectorOther" | 
/**  Raster tiles meant to be looked at — imagery, a scan, a rendered map (D11). */
"rasterImage" | 
/**
 *  Raster tiles encoding elevation, to be drawn as hillshade rather than as colour (D12).
 * 
 *  The encoding — `mapbox`, `terrarium`, `versatiles` — is deliberately not carried here yet.
 *  Nothing draws a DEM until S6.6, and that is the step that has to decide whether the encoding
 *  belongs on this enum or is re-read from `tile_schema` at the point of use.
 */
"rasterDem";

/**  One source's style: what it is, and how it is drawn. */
export type SourceStyle = SourceStyle_Serialize | SourceStyle_Deserialize;

/**  One source's style: what it is, and how it is drawn. */
export type SourceStyle_Deserialize = {
	/**  What someone said these tiles are, when the derived reading was wrong (S6.1). */
	kind?: SourceKind | null,
	appearance?: Appearance_Deserialize,
};

/**  One source's style: what it is, and how it is drawn. */
export type SourceStyle_Serialize = {
	/**  What someone said these tiles are, when the derived reading was wrong (S6.1). */
	kind: SourceKind | null,
	appearance: Appearance_Serialize,
};

/**
 *  A byte range in the document, `start..end`.
 * 
 *  Byte offsets rather than character indices because that is what text editors, `str` slicing and
 *  LSP-shaped protocols all speak. `Deserialize` too: a span makes the round trip out to a form
 *  field and back when the webview asks for the value under it to be changed.
 */
export type Span = {
	start: number,
	end: number,
};

/**  One string literal: what it means, how it was written, and where it sits. */
export type Str = {
	/**  The decoded value — escapes resolved, quotes removed. */
	value: string,
	quote: Quote,
	/**  Covers the quotes, where there are any. */
	span: Span,
};

/**  A decoded tile, layer by layer (A4). */
export type TileInspection = {
	z: number,
	x: number,
	y: number,
	/**  Bytes as stored in the container, before decompression. */
	storedBytes: number,
	layers: LayerInspection[],
};

/**  A highlighted span. Whitespace is simply absent. */
export type Token = {
	kind: TokenKind,
	span: Span,
};

/**  What a stretch of the document is, for a syntax highlighter. */
export type TokenKind = 
/**  An operation name at the head of a node. */
"operation" | 
/**  A parameter name. */
"key" | 
/**  A parameter value, quoted or bare. */
"value" | 
/**  `|`, `=`, `[`, `]`, `,` */
"punctuation" | "comment";

/**  A parameter value: one string, or a bracketed list of them. */
export type Value = {
	kind: "single",
} & Str | { kind: "array"; items: Str[]; span: Span };

/**
 *  A named view: a name, and where the camera was.
 * 
 *  **Called a bookmark until [Q38]**, and it carried a `source` — "so a view can offer to reopen
 *  it" — that nothing ever reopened, filled from whichever container happened to be mounted last.
 *  A view is a place, and a place does not belong to a file. An old file's `source` key is ignored
 *  rather than rejected, so nobody loses their views to the rename.
 * 
 *  The camera is [`Camera`] rather than five fields of its own: it is the same thing the layout
 *  restores a window to, and one type means one answer to what a camera is.
 * 
 *  [Q38]: ../../docs/decisions.md
 */
export type View = {
	name: string,
	/**
	 *  Seconds since the Unix epoch, emitted as a `number` — a double holds them exactly for the
	 *  next quarter of a million years, and `u32` would overflow in 2106.
	 */
	createdAt: number,
} & Camera;

/**  A parse failure the editor can place, rather than a rendered string it would have to read. */
export type VplError = {
	message: string,
	span: Span,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

