/**
 * Bundles MapLibre's worker into `public/maplibre-gl-worker.js` (S1.4).
 *
 * Since v6 MapLibre loads its worker from a separate file, resolved at runtime via
 * `new URL('./maplibre-gl-worker.mjs', import.meta.url)`. Bundlers inline `maplibre-gl.mjs` into a
 * chunk, so that URL stops pointing anywhere and the worker fails to start.
 *
 * Shipping a self-contained copy lets `MapCanvas.svelte` point MapLibre at a stable path. It goes in
 * `public/` so Vite copies it untouched: the worker does `import()` on a blob URL, which Vite cannot
 * analyse and warns about otherwise.
 *
 * `node-versatiles-svelte` solves the same problem with `new URL(..., import.meta.url)` because it is
 * a *library* and cannot assume a root path. Studio is an application, so a root-relative URL is both
 * available and simpler.
 *
 * The bundle is generated from the installed `maplibre-gl`, so it always matches the version the
 * main thread uses. `maplibre-gl` is pinned exactly in package.json to keep it that way.
 *
 * Approach borrowed from `node-versatiles-svelte`; the code is ours ([Q18](../docs/decisions.md)).
 */

import { build } from 'esbuild';
import { createRequire } from 'node:module';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const require = createRequire(import.meta.url);
const root = fileURLToPath(new URL('..', import.meta.url));

const entryPoint = require.resolve('maplibre-gl/dist/maplibre-gl-worker.mjs');
// `public/`, not `src/`: Vite copies it verbatim without import analysis. The worker contains a
// deliberate `import()` of a blob URL that Vite cannot analyse, and warns about on every build.
const outfile = join(root, 'public', 'maplibre-gl-worker.js');

// Guard the pin: a worker built from a different version than the main thread fails at runtime in
// ways that look like anything but a version mismatch.
const pkg = JSON.parse(await readFile(join(root, 'package.json'), 'utf8')) as {
	dependencies: Record<string, string>;
};
const pinned = pkg.dependencies['maplibre-gl'];
if (!/^\d/.test(pinned)) {
	throw new Error(`maplibre-gl must be pinned exactly, found "${pinned}" — the worker must match the main thread`);
}
const installed = JSON.parse(
	await readFile(join(dirname(require.resolve('maplibre-gl/package.json')), 'package.json'), 'utf8')
) as { version: string };
if (installed.version !== pinned) {
	throw new Error(`package.json pins maplibre-gl ${pinned} but ${installed.version} is installed`);
}

await build({
	entryPoints: [entryPoint],
	outfile,
	bundle: true,
	format: 'iife',
	platform: 'browser',
	target: 'es2022',
	minify: true,
	legalComments: 'inline',
	banner: { js: `// Generated by scripts/bundle_worker.ts from maplibre-gl ${installed.version}. Do not edit.` }
});

console.log(`Bundled maplibre-gl ${installed.version} worker → public/maplibre-gl-worker.js`);
